### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by hiddengearz** [shmilylty/OneForAll#107]
**Describe the bug**
Inside my docker container I do `python3.8 oneforall.py --target yahoo.com run` and get the following error.

```Traceback (most recent call last):
  File "oneforall.py", line 269, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 245, in run
    self.main()
  File "oneforall.py", line 199, in main
    self.data = resolve.run_resolve(self.domain, self.data)
  File "/app/OneForAll/common/resolve.py", line 192, in run_resolve
    records = deal_output(output_path)
  File "/app/OneForAll/common/resolve.py", line 128, in deal_output
    cidrs.append(asn_info.get('cidr'))
AttributeError: 'NoneType' object has no attribute 'get'
```
Sometimes it works other times it doesn't. Any advice?

**Comment by JosteinFraNorge** [comment]
I get the same error. It happens right after (or inside):
`HH:MM:SS,977 [INFOR] resolve:75 - Processing resolved results`

**Comment by shmilylty** [comment]
Clone the latest code and try again @JosteinFraNorge @hiddengearz
