### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by p1g3** [shmilylty/OneForAll#12]
09:55:02,488 [INFOR] request:113 - 正在异步进行子域的GET请求
Traceback (most recent call last):
  File "oneforall.py", line 157, in <module>
    fire.Fire(OneForAll)
  File "E:\ENV\Python3\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\ENV\Python3\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "E:\ENV\Python3\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 150, in run
    self.main()
  File "oneforall.py", line 128, in main
    self.datas = loop.run_until_complete(task)
  File "E:\ENV\Python3\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "E:\ENV\Python3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "E:\ENV\Python3\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "E:\ENV\Python3\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "E:\ENV\Python3\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Current thread 0x00000fb4 (most recent call first):
  File "E:\ENV\Python3\lib\site-packages\pycares\__init__.py", line 387 in <lambda>

**Comment by shmilylty** [comment]
可以到[config.py](./oneforall/config.py)中将limit_open_conn设置为100试试。

**Comment by p1g3** [comment]
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000210B52B1240>
transport: <_SelectorSocketTransport fd=1964 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "E:\ENV\Python3\lib\asyncio\sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "E:\ENV\Python3\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "E:\ENV\Python3\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
SSL error in data received

修改后出现连续报错，python版本3.7.3

**Comment by shmilylty** [comment]
请再次克隆最新代码使用Python 3.8试试
