### ISSUE TITLE
'config.setting' has no attribute 'module_dir'

### ISSUE THREAD

**Issue by AlecBlance** [shmilylty/OneForAll#122]
**Whether the latest code is used**
Yes

**Bug description**
The tool doesn't run because there is no attribute in the settings (config.setting)

**Operation environment**
 - System information: Windows 10 Pro x64
 - Python version: Python 3.8.2
 - OneForAll version: v0.3.0
 
**How to reproduce**
1. Step (optional)

2. Command (required)
python3 oneforall.py --target google.com run

**Error text**
Traceback (most recent call last):
  File "oneforall.py", line 287, in <module>
    fire.Fire(OneForAll)
  File "/home/epx/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/epx/.local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/epx/.local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 263, in run
    self.main()
  File "oneforall.py", line 182, in main
    collect.run()
  File "/home/epx/tools/sub/OneForAll/modules/collect.py", line 60, in run
    self.get_mod()
  File "/home/epx/tools/sub/OneForAll/modules/collect.py", line 37, in get_mod
    module_path = setting.module_dir.joinpath(module)
AttributeError: module 'config.setting' has no attribute 'module_dir'

**Expected results**
Completely run the gathering without errors

**Actual results**
A clear and concise description of the actual results (optional, such as any errors)

**Screenshot**
![Capture](https://user-images.githubusercontent.com/17378596/89648979-a16a3980-d8f2-11ea-812c-54182a19199d.PNG)

**Log upload**
[oneforall.log](https://github.com/shmilylty/OneForAll/files/5041556/oneforall.log)

**Comment by AlecBlance** [comment]
The cause is maybe you have deleted the module_dir in your latest commit (3hrs ago).

**Comment by AlecBlance** [comment]
Cloned it again and it works
