### ISSUE TITLE
在windows 下使用python3.8发现代码出问题

### ISSUE THREAD

**Issue by xigua9527-mac** [shmilylty/OneForAll#143]
**是否使用了最新代码**
是

**Bug描述**
Traceback (most recent call last):
  File "oneforall.py", line 13, in <module>
    import dbexport
  File "C:\Users\Administrator\Desktop\子域名收集工具\OneForAll-0.3.0\OneForAll-0.3.0\dbexport.py", line 13, in <module>
    from common import utils
  File "C:\Users\Administrator\Desktop\子域名收集工具\OneForAll-0.3.0\OneForAll-0.3.0\common\utils.py", line 20, in <module>
    from config.log import logger
  File "C:\Users\Administrator\Desktop\子域名收集工具\OneForAll-0.3.0\OneForAll-0.3.0\config\log.py", line 26, in <module>
    logger.level(name='TRACE', no=5, color='<cyan><bold>', icon='✏️')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\loguru\_logger.py", line 1527, in level
    raise TypeError("Level '%s' already exists, you can't update its severity no" % name)
TypeError: Level 'TRACE' already exists, you can't update its severity no
请问为什么会报错

**运行环境**
 - 系统：windows2008
 - Python版本：3.8
 - OneForAll版本：0.30
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
TypeError: Level 'TRACE' already exists, you can't update its severity no

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
下载最新的代码，https://github.com/shmilylty/OneForAll/archive/master.zip  ，然后重新安装依赖。
