### ISSUE TITLE
请填写BUG标题

### ISSUE THREAD

**Issue by miaochiahao** [shmilylty/OneForAll#146]
**是否使用了最新代码**
是

**Bug描述**
中途异常退出

**运行环境**
 - 系统：OSX
 - Python版本：3.8.5
 - OneForAll版本：0.3.0
 
**如何复现**
python3 oneforall.py --target ./domains.txt run

**报错文本**
```
12:13:34,126 [INFOR] module:65 - The QuerySPF module took 0.1 seconds found 0 subdomains
12:13:34,178 [INFOR] module:65 - The QuerySOA module took 0.1 seconds found 0 subdomains
Traceback (most recent call last):
  File "oneforall.py", line 255, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
12:13:34,327 [INFOR] module:65 - The Sublist3rQuery module took 0.6 seconds found 56 subdomains
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 242, in run
    self.main()
  File "oneforall.py", line 179, in main
    collect.run()
  File "/Users/anakin/Desktop/HackTools/OneForAll-0.3.0/modules/collect.py", line 73, in run
    thread.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
按照这里的分析应该是线程开太多了……这次跑了500个域名，建议开个限制，如果线程过多加入队列等候

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
正在优化中

**Comment by miaochiahao** [comment]
> 正在优化中

师傅辛苦了~~

**Comment by foozzi** [comment]
same issue in new version

**Comment by King-Mr** [comment]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/c9aa39e8-e663-4049-bd15-25f49e57c2e6">
 0.4.5还是有这个问题
