### ISSUE TITLE
使用--targets域名对域名列表爆破出现除0异常

### ISSUE THREAD

**Issue by wakaka6** [shmilylty/OneForAll#148]
**是否使用了最新代码**
是

**Bug描述**
使用--targets域名列表启动oneforall扫描列表中第二个域名时出现除0异常

**运行环境**
 - 系统：[例如kali2019.4 中用docker 跑ubuntu ]（必写）
 - Python版本：[例如3.8.2]（必写）
 - OneForAll版本：[例如0.3.0]（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3 oneforall.py --targets domain.txt run

**报错文本**
复制完整的报错文本（必写）
Traceback (most recent call last):
  File "oneforall.py", line 303, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 279, in run
    self.main()
  File "oneforall.py", line 203, in main
    brute.run()
  File "/OneForAll/brute.py", line 737, in run
    valid_subdomains = self.main(self.domain)
  File "/OneForAll/brute.py", line 680, in main
    self.enable_wildcard = is_enable_wildcard(domain)
  File "/OneForAll/brute.py", line 148, in is_enable_wildcard
    is_enable = detect_wildcard(domain)
  File "/OneForAll/brute.py", line 144, in detect_wildcard
    return any_similar_html(all_request_resp)
  File "/OneForAll/brute.py", line 121, in any_similar_html
    if similarity.is_similar(html_doc1, html_doc2):
  File "/OneForAll/common/similarity.py", line 134, in is_similar
    value = get_pseudodistance(html_doc1, html_doc2, dimension)
  File "/OneForAll/common/similarity.py", line 122, in get_pseudodistance
    return calc_pseudodistance(dom1_eigenvector, dom2_eigenvector, dimension)
  File "/OneForAll/common/similarity.py", line 101, in calc_pseudodistance
    pseudodistance = abs(a)/b
ZeroDivisionError: float division by zero

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![333](https://user-images.githubusercontent.com/48764488/94566851-5ae1ed00-025a-11eb-9d5e-c12af1254fea.gif)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明
第一次启动的本条命令时被我未进行操作被`killed`了
![image](https://user-images.githubusercontent.com/48764488/94568598-3ab32d80-025c-11eb-8fef-67a2d6915342.png)
domain.txt内容(运行到1688.com时就结束或者报错了)
```txt
alimama.com
1688.com
aliyun.com
dingtalk.com
alibabacloud.com
alibaba-inc.com
aliyun-inc.com
tmall.com
taobao.com
aliexpress.com
```

**Comment by shmilylty** [comment]
收到，后面我们做一下内存优化。

**Comment by wakaka6** [comment]
好的，辛苦师傅了

**Comment by shmilylty** [comment]
最新版本已做了内存优化，你可以更新OneForAll然后重新测试一下。@wakaka6
