### ISSUE TITLE
aiodns.error.DNSError: (4, b'Domain name not found')

### ISSUE THREAD

**Issue by geekmc** [shmilylty/OneForAll#15]
运行到开启爆破的时候报错如下：
Python环境为Python3.7.0

Progress:   0%| | 0/47 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "oneforall.py", line 166, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/python3/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/python3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/python3/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 159, in run
    self.main()
  File "oneforall.py", line 99, in main
    brute.run()
  File "/OneForAll/oneforall/aiobrute.py", line 282, in run
    loop.run_until_complete(self.main(self.domain, rx_queue))
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/OneForAll/oneforall/aiobrute.py", line 253, in main
    results = await pool.map(resolve.aiodns_query_a, task)
  File "/usr/local/python3/lib/python3.7/site-packages/aiomultiprocess/core.py", line 434, in map
    return await self.results(tids)
  File "/usr/local/python3/lib/python3.7/site-packages/aiomultiprocess/core.py", line 398, in results
    raise ProxyException(tb)
aiomultiprocess.core.ProxyException: Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/aiomultiprocess/core.py", line 298, in run
    result = future.result()
  File "/OneForAll/oneforall/common/resolve.py", line 54, in aiodns_query_a
    answers = await resolver.query(hostname, 'A')
aiodns.error.DNSError: (4, b'Domain name not found')

**Comment by shmilylty** [comment]
请重新克隆到一个地方再跑试试

**Comment by shmilylty** [comment]
已做修改，请再试试。https://github.com/shmilylty/OneForAll/commit/515bd34c7e2ddaad16bf6b570c66ff76fc905fef
