### ISSUE TITLE
无法运行OneForAll

### ISSUE THREAD

**Issue by jobsgxx** [shmilylty/OneForAll#150]
运行提示报错如下：
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import dbexport
  File "/mydata/Security/Attack_Tools/OneForAll-0.3.0/dbexport.py", line 13, in <module>
    from common import utils
  File "/mydata/Security/Attack_Tools/OneForAll-0.3.0/common/utils.py", line 20, in <module>
    from config.log import logger
  File "/mydata/Security/Attack_Tools/OneForAll-0.3.0/config/log.py", line 26, in <module>
    logger.level(name='TRACE', no=5, color='<cyan><bold>', icon='✏️')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/loguru/_logger.py", line 1527, in level
    raise TypeError("Level '%s' already exists, you can't update its severity no" % name)
TypeError: Level 'TRACE' already exists, you can't update its severity no

**Comment by BugHunter001** [comment]
first update your python3 and pip3 and type pip3 install -r requirements.txt  it fixed everything mine you can try this

**Comment by shmilylty** [comment]
@jobsgxx Excuse me, has this problem been solved?

**Comment by Chr1sto-l** [comment]
Traceback (most recent call last):
  File "oneforall.py", line 255, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 242, in run
    self.main()
  File "oneforall.py", line 179, in main
    collect.run()
  File "/opt/Sparta/tools/OneForAll/modules/collect.py", line 60, in run
    self.import_func()
  File "/opt/Sparta/tools/OneForAll/modules/collect.py", line 49, in import_func
    import_object = importlib.import_module('.' + name, package)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/Sparta/tools/OneForAll/modules/check/cert.py", line 7, in <module>
    import ssl
  File "/usr/local/python3/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

**Comment by Chr1sto-l** [comment]
> @jobsgxx Excuse me, has this problem been solved?

Do you have the same problem

**Comment by shmilylty** [comment]
> Traceback (most recent call last):
> File "oneforall.py", line 255, in
> fire.Fire(OneForAll)
> File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
> component_trace = _Fire(component, args, parsed_flag_args, context, name)
> File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
> component, remaining_args = _CallAndUpdateTrace(
> File "/usr/local/python3/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
> component = fn(*varargs, **kwargs)
> File "oneforall.py", line 242, in run
> self.main()
> File "oneforall.py", line 179, in main
> collect.run()
> File "/opt/Sparta/tools/OneForAll/modules/collect.py", line 60, in run
> self.import_func()
> File "/opt/Sparta/tools/OneForAll/modules/collect.py", line 49, in import_func
> import_object = importlib.import_module('.' + name, package)
> File "/usr/local/python3/lib/python3.8/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1014, in _gcd_import
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "", line 783, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/opt/Sparta/tools/OneForAll/modules/check/cert.py", line 7, in
> import ssl
> File "/usr/local/python3/lib/python3.8/ssl.py", line 98, in
> import _ssl # if we can't import it, let the error propagate
> ModuleNotFoundError: No module named '_ssl'

https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl
