### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by 1yuhao** [shmilylty/OneForAll#16]
报错信息
```
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x12cb1add8>
transport: <_SelectorSocketTransport fd=30 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python/3.7
```
---
修复方法
common文件夹下request.py文件
图中 的BaesException as e: 修改为except BaseException as e:

**Comment by shmilylty** [comment]
已经修复https://github.com/shmilylty/OneForAll/commit/16d3530ac3ba85f8468f2f3f8937eb08df7ed309
