### ISSUE TITLE
Expects only one row when using RecordCollection.one

### ISSUE THREAD

**Issue by Dialem** [shmilylty/OneForAll#163]
Traceback (most recent call last):
  File "OneForAll/oneforall.py", line 273, in <module>
    fire.Fire(OneForAll)
  File "/home/user/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/.local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.name)
  File "/home/user/.local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "OneForAll/oneforall.py", line 250, in run
    self.main()
  File "OneForAll/oneforall.py", line 201, in main
    finder.run(self.domain, self.data, self.port)
  File "/home/user/subdomain-reconer/OneForAll/modules/finder.py", line 25, in run
    found_subdomains = find_subdomains(domain, data)
  File "/home/user/subdomain-reconer/OneForAll/modules/finder.py", line 190, in find_subdomains
    rsp_html = db.get_resp_by_url(domain, req_url)
  File "/home/user/subdomain-reconer/OneForAll/common/database.py", line 257, in get_resp_by_url
    return self.query(sql).scalar()
  File "/home/user/subdomain-reconer/OneForAll/common/records.py", line 244, in scalar
    row = self.one()
  File "/home/user/subdomain-reconer/OneForAll/common/records.py", line 238, in one
    raise ValueError('RecordCollection contained more than one row. '
ValueError: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one
The error occurs when searching for subdomains lazada.com.my

**Comment by KinofRikin** [comment]
同遇到该问题

**Comment by shmilylty** [comment]
更新再试一下呢。

**Comment by KinofRikin** [comment]
更新之后还是会报错

**Comment by KinofRikin** [comment]
![image](https://user-images.githubusercontent.com/18413058/99980278-06cf3100-2de3-11eb-985a-3e32ff9244a1.png)

**Comment by shmilylty** [comment]
> 更新之后还是会报错

执行的完整命令是什么？

**Comment by KinofRikin** [comment]
我是直接删了原项目，然后重新git clone新项目，然后运行的环境是Ubuntu 20版本，执行命令为：python3 oneforall.py --target domain --ports 80,443,8080 run

**Comment by KinofRikin** [comment]
python3 oneforall.py --target domain --port medium run 依然报错

**Comment by KinofRikin** [comment]
测试发现，在api.py里设置了key以后会报该错误，而api.py里面的key都为空时，能正常运行。

**Comment by shmilylty** [comment]
已经复现该问题，之后修复以下。

**Comment by KinofRikin** [comment]
师傅修复了嘛，目前好像问题还存在

**Comment by shmilylty** [comment]
> 师傅修复了嘛，目前好像问题还存在

暂时还没有时间修复

**Comment by shmilylty** [comment]
@KinofRikin @Dialem 可以使用最新代码再测试一下
