### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by xxsmile123** [shmilylty/OneForAll#171]
**是否使用了最新代码**
是

**Bug描述**
# python3 oneforall.py --help
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/root/tools/subdomain/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/root/tools/subdomain/OneForAll/common/utils.py", line 20, in <module>
    from common.database import Database
  File "/root/tools/subdomain/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 17, in <module>
    settings = Settings()
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 12, in __init__
    setting = importlib.import_module(setting_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/tools/subdomain/OneForAll/config/setting.py", line 40
    <<<<<<< Updated upstream
    ^
SyntaxError: invalid syntax

**运行环境**
 - 系统：deibian 9 x64（必写）
 - Python版本：[3.8.6]（必写）
 - OneForAll版本：[例如0.4.3]（必写）
 
**如何复现**
复现步骤（选写）
# python3 oneforall.py --help
复现命令（必写）
# python3 oneforall.py --help
**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）
# python3 oneforall.py --help
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/root/tools/subdomain/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/root/tools/subdomain/OneForAll/common/utils.py", line 20, in <module>
    from common.database import Database
  File "/root/tools/subdomain/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 17, in <module>
    settings = Settings()
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 12, in __init__
    setting = importlib.import_module(setting_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/tools/subdomain/OneForAll/config/setting.py", line 40
    <<<<<<< Updated upstream
    ^
SyntaxError: invalid syntax
**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）
# python3 oneforall.py --help
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/root/tools/subdomain/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/root/tools/subdomain/OneForAll/common/utils.py", line 20, in <module>
    from common.database import Database
  File "/root/tools/subdomain/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 17, in <module>
    settings = Settings()
  File "/root/tools/subdomain/OneForAll/config/__init__.py", line 12, in __init__
    setting = importlib.import_module(setting_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/tools/subdomain/OneForAll/config/setting.py", line 40
    <<<<<<< Updated upstream
    ^
SyntaxError: invalid syntax
**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by STR17E** [comment]
Did you solve your problem, please?

**Comment by shmilylty** [comment]
换一个Linux系统会复现这个问题吗

**Comment by xxsmile123** [comment]
我重新安装了，已经解决了。谢谢
