### ISSUE TITLE
docker 版本运行报错 ”ModuleNotFoundError: No module named 'config.log'“

### ISSUE THREAD

**Issue by Wh0ale** [shmilylty/OneForAll#177]
**是否使用了最新代码**
是

**Bug描述**
ModuleNotFoundError: No module named 'config.log'

**运行环境**
 - 系统：Linux kali 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux
 - docker 版本：shmilylty/oneforall              latest               b45ff23b2fe6        8 hours ago  
 
**如何复现**
`docker run -it --rm -v ~/results:/OneForAll/results -v ~/.config:/OneForAll/config b45ff23b2fe6 --target example.com run`

复现命令（必写）
`docker run -it --rm -v ~/results:/OneForAll/results -v ~/.config:/OneForAll/config b45ff23b2fe6 --target example.com run`

**报错文本**
```
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/OneForAll/common/utils.py", line 20, in <module>
    from common.database import Database
  File "/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
ModuleNotFoundError: No module named 'config.log'
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/44937351/104817987-bbc02000-585f-11eb-8153-9b7d618e7e6d.png)

**Comment by Wh0ale** [comment]
是我文件路径的问题，已解决。
