### ISSUE TITLE
欢迎推荐新的子域查询接口

### ISSUE THREAD

**Issue by shmilylty** [shmilylty/OneForAll#184]
目前OneForAll许多[子域收集模块](https://github.com/shmilylty/OneForAll/blob/master/docs/collection_modules.md)，如果你发现有OneForAll中没有但是比较好使的子域查询接口欢迎在下方推荐，推荐时尽量详细的说明一下，我会在研判之后考虑实现并添加到OneForAll中。

**Comment by jhhd88** [comment]
可以考虑加一下https://quake.360.cn/

**Comment by shmilylty** [comment]
> 可以考虑加一下https://quake.360.cn/

这个感觉不是很强，后面可以考虑添加。

**Comment by kuron3k0** [comment]
大佬有考虑加查备案号、子公司、whois反查之类的方法吗

**Comment by shmilylty** [comment]
> 大佬有考虑加查备案号、子公司、whois反查之类的方法吗

以后做成信息收集平台时会考虑。

**Comment by Tren** [comment]
可以添加一下 https://dns.bufferover.run/dns?q=  这个网站 平常使用非常不错

**Comment by jhhd88** [comment]
> 可以添加一下 https://dns.bufferover.run/dns?q= 这个网站 平常使用非常不错

这个很不错

**Comment by tgllsy** [comment]
https://rapiddns.io/

**Comment by shmilylty** [comment]
> 可以添加一下 https://dns.bufferover.run/dns?q= 这个网站 平常使用非常不错

这个收集接口已有实现

**Comment by jhhd88** [comment]
> 师傅 看下这个https://api-docs.fullhunt.io/#introduction

这个不错啊，用api链接可以直接获取数据，没有限制

https://fullhunt.io/api/v1/domain/baidu.com/subdomains

**Comment by jhhd88** [comment]
> 师傅 看下这个https://api-docs.fullhunt.io/#introduction

注册了的是300个结果限制，不注册，直接api链接获取是400个结果限制。233

![image](https://user-images.githubusercontent.com/15847202/141318316-fb2e25dd-a433-4f7a-a04b-db3b78257d99.png)
![image](https://user-images.githubusercontent.com/15847202/141318363-bd501a8d-4613-4eeb-9829-eb262511ea0d.png)

**Comment by shmilylty** [comment]
> > 师傅 看下这个https://api-docs.fullhunt.io/#introduction
> 
> 这个不错啊，用api链接可以直接获取数据，没有限制
> 
> https://fullhunt.io/api/v1/domain/baidu.com/subdomains
> 
> 不过注册账户以后有3000的结果限制，未注册的只能获取400个结果。
> 
> ![image](https://user-images.githubusercontent.com/15847202/141318908-86b34c01-291e-4db3-9571-a3afa77dbc94.png)

已添加查询模块

**Comment by ring007c** [comment]
https://hunter.qianxin.com/  添加下这个

**Comment by shmilylty** [comment]
> https://hunter.qianxin.com/ 添加下这个

有的

**Comment by kN6jq** [comment]
师傅  这个加一下
https://omnisint.io/

**Comment by shmilylty** [comment]
> 师傅 这个加一下 https://omnisint.io/

后面有空加一下

**Comment by 1946Dream** [comment]
https://myssl.com 可以添加一下这个吗？

**Comment by pwnhxl** [comment]
https://urlscan.io/api/v1/search/?q=domain:163.com
https://myssl.com/api/v1/discover_sub_domain?domain=163.com
这两个好像不错 师傅加下

**Comment by shmilylty** [comment]
> https://rapiddns.io/

这个已有实现

**Comment by shmilylty** [comment]
> 师傅 这个加一下 https://omnisint.io/

这个网站打不开了

**Comment by shmilylty** [comment]
> https://myssl.com 可以添加一下这个吗？

已添加https://github.com/shmilylty/OneForAll/commit/682b26120fc40e7eafeca0ca8a368fa84fa41fab

**Comment by shmilylty** [comment]
> https://urlscan.io/api/v1/search/?q=domain:163.com https://myssl.com/api/v1/discover_sub_domain?domain=163.com 这两个好像不错 师傅加下

已添加 
https://github.com/shmilylty/OneForAll/commit/682b26120fc40e7eafeca0ca8a368fa84fa41fab
https://github.com/shmilylty/OneForAll/commit/409e2a68124bc217f64de738c5de3f944c321d71

**Comment by shmilylty** [comment]
> 可以考虑加一下https://quake.360.cn/

已添加 https://github.com/shmilylty/OneForAll/commit/20cdf09aec5d0040840026b04ae7c7d602e78fe8

**Comment by Old-stan** [comment]
ipv4info已经下线了，可以去掉

**Comment by ammu51** [comment]
┌──(root㉿boss)-[/home/hacker/OneForAll]
└─# ./oneforall.py --target flipkart.com run
Traceback (most recent call last):
  File "/home/hacker/OneForAll/./oneforall.py", line 15, in <module>
    import export
  File "/home/hacker/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/home/hacker/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/home/hacker/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/home/hacker/OneForAll/config/log.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
    
HOW I SOLVED THIS ERROR

**Comment by Ge0metryAI** [comment]
> ┌──(root㉿boss)-[/home/hacker/OneForAll] └─# ./oneforall.py --target flipkart.com run Traceback (most recent call last): File "/home/hacker/OneForAll/./oneforall.py", line 15, in import export File "/home/hacker/OneForAll/export.py", line 13, in from common import utils File "/home/hacker/OneForAll/common/utils.py", line 21, in from common.database import Database File "/home/hacker/OneForAll/common/database.py", line 8, in from config.log import logger File "/home/hacker/OneForAll/config/log.py", line 4, in from loguru import logger ModuleNotFoundError: No module named 'loguru'
> 
> HOW I SOLVED THIS ERROR

pip install loguru
