### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by topsekadmin** [shmilylty/OneForAll#185]
报错信息如下：
```
Traceback (most recent call last):
  File "oneforall.py", line 273, in <module>
17:50:11,503 [INFOR]     brutefire.Fire(OneForAll):
201  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 138, in Fire
 -     component_trace = _Fire(component, args, parsed_flag_args, context, name)Counting IP cname appear times

  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 250, in run
    self.main()
  File "oneforall.py", line 171, in main
    brute.run()
  File "E:\Pentration Tools\域名爆破\OneForAll-0.4.3\brute.py", line 477, in run
    valid_subdomains = self.main(self.domain)
  File "E:\Pentration Tools\域名爆破\OneForAll-0.4.3\brute.py", line 450, in main
    appear_times = stat_appear_times(output_path)
  File "E:\Pentration Tools\域名爆破\OneForAll-0.4.3\brute.py", line 204, in stat_appear_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Pentration Tools\\域名爆破\\OneForAll-0.4.3\\results\\temp\\resolved_result_xiaowoxuetang.com_20210128_175011.json'
```

**Comment by shmilylty** [comment]
> "E:\Pentration Tools\域名爆破\OneForAll-0.4.3\brute.py"

目录不要有空格

**Comment by topsekadmin** [comment]
> > "E:\Pentration Tools\域名爆破\OneForAll-0.4.3\brute.py"
> 
> 目录不要有空格

谢大佬，已解决

**Comment by topsekadmin** [comment]
已解决
