### ISSUE TITLE
引发ValueError('RecordCollection包含多于一行。') ValueError: RecordCollection包含多于一行。使用RecordCollection.one时只期望一行

### ISSUE THREAD

**Issue by yuebinge** [shmilylty/OneForAll#199]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
raise ValueError('RecordCollection contained more than one row. '
ValueError: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.3.0]（必写）
kali2020.1
python3.7.6
oneforall0.4.3
 
**如何复现**
复现步骤（选写）
python3 oneforall.py --targets ./target.txt run

复现命令（必写）
python3 oneforall.py --targets ./target.txt run
**报错文本**
复制完整的报错文本（必写）
23:40:07,930 [INFOR] finder:23 - Start Finder module
Traceback (most recent call last):
  File "oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 254, in run
    self.main()
  File "oneforall.py", line 205, in main
    finder.run(self.domain, self.data, self.port)
  File "/root/Desktop/OneForAll-master/modules/finder.py", line 25, in run
    found_subdomains = find_subdomains(domain, data)
  File "/root/Desktop/OneForAll-master/modules/finder.py", line 190, in find_subdomains
    rsp_html = db.get_resp_by_url(domain, req_url)
  File "/root/Desktop/OneForAll-master/common/database.py", line 258, in get_resp_by_url
    return self.query(sql).scalar()
  File "/root/Desktop/OneForAll-master/common/records.py", line 244, in scalar
    row = self.one()
  File "/root/Desktop/OneForAll-master/common/records.py", line 238, in one
    raise ValueError('RecordCollection contained more than one row. '
ValueError: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one
Request Progress: 341it [00:40,  8.35it/s]
root@kali:~/Desktop/OneForAll-master# 

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by dead5nd** [comment]
遇到了同样的问题

**Comment by saucer-man** [comment]
同样遇到这个问题，没有动代码就跑不起来，这个bug没人解吗？

**Comment by je5442804** [comment]
我这里也有，常常出现在待检测子域名十万以上的时候(我也不知道为什么会有十万这么多)

**Comment by KingXS** [comment]
how to solve it

**Comment by TARI0510** [comment]
> 可以通过设置config/setting.py 中 enable_finder_module为False 暂时性解决

感觉这样可能收集少不少子域呀。

**Comment by shmilylty** [comment]
现在还有此问题吗？
