### ISSUE TITLE
don,t know why showing this 

### ISSUE THREAD

**Issue by Fawadkhanfk** [shmilylty/OneForAll#207]
/bin/sh: 1: /root/my: not found
Traceback (most recent call last):
  File "/root/my tools/OneForAll/oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 141, in Fire
06:46:55,243 [INFOR] brute:201 - Counting IP cname appear times
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/my tools/OneForAll/oneforall.py", line 254, in run
    self.main()
  File "/root/my tools/OneForAll/oneforall.py", line 171, in main
    brute.run()
  File "/root/my tools/OneForAll/brute.py", line 477, in run
    valid_subdomains = self.main(self.domain)
  File "/root/my tools/OneForAll/brute.py", line 450, in main
    appear_times = stat_appear_times(output_path)
  File "/root/my tools/OneForAll/brute.py", line 204, in stat_appear_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/root/my tools/OneForAll/results/temp/resolved_result_google.com_20210622_064654.json'

**Comment by shmilylty** [comment]
Do not have spaces in the directory
