### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by xxsmile123** [shmilylty/OneForAll#209]
**是否使用了最新代码**
是

**Bug描述**
更新完项目，直接批量跑四个主域名
出现如下报错：
# python3 oneforall.py --targets targets.txt run

OneForAll is a powerful subdomain integration tool
             ___             _ _ 
 ___ ___ ___|  _|___ ___ ___| | | {v0.4.3 #dev}
| . |   | -_|  _| . |  _| .'| | | 
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll is under development, please update before each use!

[*] Starting OneForAll @ 2021-06-30 21:54:48

21:54:48,842 [INFOR] utils:523 - Checking dependent environment
21:54:48,843 [INFOR] utils:535 - Checking network environment
21:54:48,862 [INFOR] utils:546 - Checking for the latest version
21:54:49,028 [INFOR] utils:570 - The current version v0.4.3 is already the latest version
21:54:49,032 [INFOR] oneforall:243 - Start running OneForAll
21:54:49,037 [INFOR] oneforall:248 - Got 4 domains
Traceback (most recent call last):
  File "oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 254, in run
    self.main()
  File "oneforall.py", line 150, in main
    utils.init_table(self.domain)
  File "/root/tools/OneForAll/common/utils.py", line 777, in init_table
    db = Database()
  File "/root/tools/OneForAll/common/database.py", line 14, in __init__
    self.conn = self.get_conn(db_path)
  File "/root/tools/OneForAll/common/database.py", line 32, in get_conn
    db = records.Database(db_path)  # 不存在数据库时会新建一个数据库
  File "/root/tools/OneForAll/common/records.py", line 261, in __init__
    self._engine = create_engine(self.db_url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 430, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

尝试使用pip下载_sqlite3模块，但是提示如下错误：
# python3 -m pip install _sqlite3
ERROR: Invalid requirement: '_sqlite3'

**运行环境**
 - 系统：centos7
 - Python版本：3.8.7
 - OneForAll版本：v0.4.3 #dev
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3 oneforall.py --targets targets.txt run

**报错文本**
复制完整的报错文本（必写）
# python3 oneforall.py --targets targets.txt run

OneForAll is a powerful subdomain integration tool
             ___             _ _ 
 ___ ___ ___|  _|___ ___ ___| | | {v0.4.3 #dev}
| . |   | -_|  _| . |  _| .'| | | 
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll is under development, please update before each use!

[*] Starting OneForAll @ 2021-06-30 21:54:48

21:54:48,842 [INFOR] utils:523 - Checking dependent environment
21:54:48,843 [INFOR] utils:535 - Checking network environment
21:54:48,862 [INFOR] utils:546 - Checking for the latest version
21:54:49,028 [INFOR] utils:570 - The current version v0.4.3 is already the latest version
21:54:49,032 [INFOR] oneforall:243 - Start running OneForAll
21:54:49,037 [INFOR] oneforall:248 - Got 4 domains
Traceback (most recent call last):
  File "oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 254, in run
    self.main()
  File "oneforall.py", line 150, in main
    utils.init_table(self.domain)
  File "/root/tools/OneForAll/common/utils.py", line 777, in init_table
    db = Database()
  File "/root/tools/OneForAll/common/database.py", line 14, in __init__
    self.conn = self.get_conn(db_path)
  File "/root/tools/OneForAll/common/database.py", line 32, in get_conn
    db = records.Database(db_path)  # 不存在数据库时会新建一个数据库
  File "/root/tools/OneForAll/common/records.py", line 261, in __init__
    self._engine = create_engine(self.db_url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 430, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/43473886/124054544-c4469480-da54-11eb-9cfa-ce4760a9eafe.png)

**Comment by klmyssn** [comment]
师傅这个问题你解决了吗，我总感觉是Python的问题，我之前没升级Python的时候都是好的，升级完就也出现了这个bug

**Comment by JrDw0** [comment]
可以看看
https://stackoverflow.com/questions/1210664/no-module-named-sqlite3
https://blog.csdn.net/panguangyuu/article/details/93906484
看起来是多版本冲突的问题，最好还是建议使用pipenv或者virtualenv单独起一个python版本来跑oneforall
