### ISSUE TITLE
Python crash

### ISSUE THREAD

**Issue by adrian-rt** [shmilylty/OneForAll#210]
**Whether the latest code is used**
yes

**Bug description**

Python exception not caught while scanning a list of targets

**Operation environment**
 - System information: Ubuntu 20
 - Python version: 3.9.2
 - OneForAll version: latest from git
 
**How to reproduce**
1. Step (optional)

./oneforall.py --targets ../hosts.txt run

2. Command (required)

**Error text**
Copy the complete error text (required)

**Expected results**
A clear and concise description of the expected results (optional, such as what a normal situation should look like)

**Actual results**

Request Progress:  95%|████████████████████▉ | 101/106 [00:00<00:00, 136.09it/s]06:55:45,828 [ALERT] utils:273 - GET https://www.virustotal.com/api/v3/domains/meteoblue.com/subdomains?limit=40 429 - Too Many Requests 98                                                                                                                                                                                         
06:55:45,829 [ALERT] utils:282 - {'error': {'message': 'Quota exceeded', 'code': 'QuotaExceededError'}}
06:55:45,841 [INFOR] module:63 - VirusTotalAPIQuery module took 136.5 seconds found 30 subdomains
06:55:46,118 [ALERT] utils:273 - GET https://www.virustotal.com/api/v3/domains/meteoblue.com/subdomains?limit=40 429 - Too Many Requests 98
06:55:46,151 [ALERT] utils:282 - {'error': {'message': 'Quota exceeded', 'code': 'QuotaExceededError'}}
06:55:46,164 [INFOR] module:63 - VirusTotalAPIQuery module took 286.2 seconds found 30 subdomains
06:55:46,274 [INFOR] request:264 - Found that meteoblue.com has 91 alive subdomains
06:55:46,274 [INFOR] finder:23 - Start Finder module
Traceback (most recent call last):
  File "/home/kali/tools/OneForAll/oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/home/kali/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/kali/.local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/kali/.local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/kali/tools/OneForAll/oneforall.py", line 254, in run
    self.main()
  File "/home/kali/tools/OneForAll/oneforall.py", line 205, in main
    finder.run(self.domain, self.data, self.port)
  File "/home/kali/tools/OneForAll/modules/finder.py", line 25, in run
    found_subdomains = find_subdomains(domain, data)
  File "/home/kali/tools/OneForAll/modules/finder.py", line 190, in find_subdomains
    rsp_html = db.get_resp_by_url(domain, req_url)
  File "/home/kali/tools/OneForAll/common/database.py", line 258, in get_resp_by_url
    return self.query(sql).scalar()
  File "/home/kali/tools/OneForAll/common/records.py", line 244, in scalar
    row = self.one()
  File "/home/kali/tools/OneForAll/common/records.py", line 238, in one
    raise ValueError('RecordCollection contained more than one row. '
ValueError: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one
Request Progress: 107it [00:13,  8.02it/s]                                      
![oneforall-error](https://user-images.githubusercontent.com/1128817/125440966-92093623-402e-4f22-ad2a-e790d7a64712.png)

**Screenshot**
Screenshot of complete OneForAll execution process (recommended upload)

**Log upload**
Upload oneforall.log files (it is recommended to upload logs in case of complex problems)

**Supplementary information**
Some other supplementary notes about bug

**Comment by shmilylty** [comment]
repeat #199

**Comment by gauravlinux** [comment]
ython3 oneforall.py facebook.com run

Traceback (most recent call last):
  File "/home/kali/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/home/kali/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/home/kali/.local/lib/python3.11/site-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)



oneforall is not working please help i follow all the steps
