### ISSUE TITLE
正常执行报错没有massdns_darwin_arm64文件，是不是不兼容macbook pro M1版本呢？

### ISSUE THREAD

**Issue by uunnsec** [shmilylty/OneForAll#220]
**是否使用了最新代码**
是

**Bug描述**
运行后报错

**运行环境**
 - 系统：macbook pro M1
 - Python版本：3.9
 - OneForAll版本：0.4.3
 
**如何复现**
python3 oneforall.py --target test.com run

**报错文本**
Traceback (most recent call last):
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "/opt/homebrew/lib/python3.9/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/homebrew/lib/python3.9/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/homebrew/lib/python3.9/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/oneforall.py", line 254, in run
    self.main()
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/oneforall.py", line 171, in main
    brute.run()
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/brute.py", line 477, in run
    valid_subdomains = self.main(self.domain)
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/brute.py", line 420, in main
    massdns_path = utils.get_massdns_path(massdns_dir)
  File "/Users/zxh/sofeware/src/subDomain/OneForAll/common/utils.py", line 615, in get_massdns_path
    path.chmod(S_IXUSR)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1329, in chmod
    self._accessor.chmod(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zxh/sofeware/src/subDomain/OneForAll/thirdparty/massdns/massdns_darwin_arm64'

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
自己编译一个massdns，改名为massdns_darwin_arm64放到OneForAll/thirdparty/massdns/massdns_darwin_arm64

**Comment by lzskyline** [comment]
有Rosetta的话直接复制OneForAll/thirdparty/massdns/massdns_darwin_x86_64为OneForAll/thirdparty/massdns/massdns_darwin_arm64即可
