### ISSUE TITLE
子域名探测的时候ssl报错

### ISSUE THREAD

**Issue by littleheary** [shmilylty/OneForAll#24]
**是否使用了最新代码**
是

**Bug描述**
运行到异步进行子域的get请求时，开始出现大量的ssl报错 

**如何复现**
复现步骤（可不写）
复现命令

**预期结果**
清晰而简洁的预期结果描述（可不写）

**实际结果**
11:13:40,548 [INFOR] request:146 - 正在异步进行子域的GET请求
Progress:  38%|▍| 3978/10345 [02:00<00:06, 1025.56it/s]ERROR:asyncio:SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f326d824470>
transport: <_SelectorSocketTransport fd=808 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Progress:  49%|▍| 5080/10345 [02:36<00:47, 111.25it/s]ERROR:asyncio:SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3235e019b0>
transport: <_SelectorSocketTransport fd=787 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1056)

**屏幕截图**

**运行环境**
 - 系统：kali2
 - Python版本：Python 3.7.2+
- OneForAll版本：当前最新版

**报错文本**
ERROR:asyncio:SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f326d824470>
transport: <_SelectorSocketTransport fd=808 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Progress:  49%|▍| 5080/10345 [02:36<00:47, 111.25it/s]ERROR:asyncio:SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3235e019b0>
transport: <_SelectorSocketTransport fd=787 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1056)

**Comment by shmilylty** [comment]
已解决

**Comment by adra2n** [comment]
咋解决的？
