### ISSUE TITLE
Exception in thread riskiq_api

### ISSUE THREAD

**Issue by websecer** [shmilylty/OneForAll#241]
环境：
ubuntu20
Python 3.9.5
pip 21.3.1
`Exception in thread riskiq_api:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/romanee/OneForAll/modules/intelligence/riskiq_api.py", line 53, in run
    query.run()
  File "/home/romanee/OneForAll/modules/intelligence/riskiq_api.py", line 39, in run
    self.query()
  File "/home/romanee/OneForAll/modules/intelligence/riskiq_api.py", line 27, in query
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 891, in json
    return complexjson.loads(
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by carry-pan** [comment]
riskiq_api.py修改下，指定content-type类型：
self.header = {"Content-Type":"application/json", "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"}

![image](https://user-images.githubusercontent.com/47935274/147467875-1664a161-d9e2-4b48-b918-e706a3ec71ea.png)

**Comment by websecer** [comment]
感谢老哥解答，已经解决了

**Comment by shmilylty** [comment]
改问题已解决 https://github.com/shmilylty/OneForAll/blob/master/modules/intelligence/riskiq_api.py#L20
