### ISSUE TITLE
metadata-generation-failed on install

### ISSUE THREAD

**Issue by mastercho** [shmilylty/OneForAll#249]
**Whether the latest code is used**
Yes

**Bug description**
After I run 
`pip3 install -r requirements.txt` got error

error: metadata-generation-failed

**Operation environment**
 - System information: Windows 10 x64
 - Python version: 3.82
 - OneForAll version: Latest commit
 
**How to reproduce**
1. Clone latest commit

2. `pip3 install -r requirements.txt`

**Error text**
```
Collecting fire==0.4.0
  Using cached fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ninja\AppData\Local\Temp\pip-install-5qxs3z24\fire_921c86302b774a329d3aa1b737db49bf\setup.py", line 46, in <module>
          setup(
        File "c:\python38\lib\site-packages\setuptools\__init__.py", line 154, in setup
          _install_setup_requires(attrs)
        File "c:\python38\lib\site-packages\setuptools\__init__.py", line 143, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "c:\python38\lib\site-packages\setuptools\__init__.py", line 135, in __init__
          super().__init__(filtered)
        File "c:\python38\lib\site-packages\setuptools\dist.py", line 456, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 996, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\_itertools.py", line 16, in unique_everseen
          k = key(element)
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 931, in _normalized_name
          return self._name_from_stem(stem) or super()._normalized_name
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 600, in _normalized_name
          return Prepared.normalize(self.name)
        File "c:\python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 855, in normalize
          return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
        File "c:\python38\lib\re.py", line 208, in sub
          return _compile(pattern, flags).sub(repl, string, count)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by shmilylty** [comment]
现在问题解决了吗
