### ISSUE TITLE
invalid IP address

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#25]
**是否使用了最新代码**
是

**Bug描述**
一到域名爆破的时候就出现无效IP的错误提示.

**如何复现**
使用了自己的subname文件,不知道是不是因为文件里有特殊字符引起的.

**预期结果**
清晰而简洁的预期结果描述（可不写）

**实际结果**
清晰而简洁的实际结果描述（如出现什么错误）

**屏幕截图**
![微信图片_20190929181112](https://user-images.githubusercontent.com/15847202/65830726-c2322d80-e2e4-11e9-95a8-ac6c169e7e0e.png)

**运行环境**
 - 系统：Windows 7 x64
 - Python版本：3.7.4
- OneForAll版本：0.0.6

**报错文本**
`Progress:   0%| | 0/366 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "oneforall.py", line 166, in <module>
    fire.Fire(OneForAll)
  File "C:\Python37\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Python37\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Python37\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 159, in run
    self.main()
  File "oneforall.py", line 99, in main
    brute.run()
  File "E:\tools\OneForAll\oneforall\aiobrute.py", line 284, in run
    loop.run_until_complete(self.main(self.domain, rx_queue))
  File "C:\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "E:\tools\OneForAll\oneforall\aiobrute.py", line 255, in main
    results = await pool.map(resolve.aiodns_query_a, task)
  File "C:\Python37\lib\site-packages\aiomultiprocess\core.py", line 434, in map
    return await self.results(tids)
  File "C:\Python37\lib\site-packages\aiomultiprocess\core.py", line 398, in results
    raise ProxyException(tb)
aiomultiprocess.core.ProxyException: Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\aiomultiprocess\core.py", line 298, in run
    result = future.result()
  File "E:\tools\OneForAll\oneforall\common\resolve.py", line 53, in aiodns_query_a
    resolver = aiodns_resolver()
  File "E:\tools\OneForAll\oneforall\common\resolve.py", line 41, in aiodns_resolver
    timeout=config.resolver_timeout)
  File "C:\Python37\lib\site-packages\aiodns\__init__.py", line 46, in __init__
    self.nameservers = nameservers
  File "C:\Python37\lib\site-packages\aiodns\__init__.py", line 59, in nameservers
    self._channel.servers = value
  File "C:\Python37\lib\site-packages\pycares\__init__.py", line 433, in servers
    raise ValueError("invalid IP address")
ValueError: invalid IP address`

**Comment by shmilylty** [comment]
已不再使用pycares库，应该不会再报这个错误了。
