### ISSUE TITLE
使用docker版报No module named 'config.log'

### ISSUE THREAD

**Issue by Explore-c** [shmilylty/OneForAll#262]
**是否使用了最新代码**
是

**Bug描述**
运行提示这个：
```
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
ModuleNotFoundError: No module named 'config.log'

```

**运行环境**
 - 系统：centos7
 - Python版本：无
 - OneForAll版本：最新
 
**如何复现**
docker run -it --rm -v ~/results:/OneForAll/results -v ~/.config:/OneForAll/config shmilylty/oneforall --target baidu.com run

**报错文本**
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
ModuleNotFoundError: No module named 'config.log'

**预期结果**
正常运行

**实际结果**

**屏幕截图**

![image](https://user-images.githubusercontent.com/46821530/175482594-ed42c0db-80c9-47d3-8f36-d683f297367d.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by Tardis07** [comment]
请不要直接套用指令，启动容器之前要先配置好config目录里相关的配置文件。详细步骤在README.md里面都有描述，请仔细阅读。
