### ISSUE TITLE
Python 3.11版本无法使用 因为缺少sre_parse库

### ISSUE THREAD

**Issue by yz1639** [shmilylty/OneForAll#291]
**是否使用了最新代码**
是

**Bug描述**
```
ImportError: cannot import name 'sre_parse' from 're'
```

**运行环境**
 - 系统：Windows 11 x64
 - Python版本：3.11
 - OneForAll版本：0.4.5
 
**如何复现**
直接用python311运行即可

复现命令
python .\oneforall.py

**报错文本**
```
python311 .\oneforall.py
Traceback (most recent call last):
  File "D:\infiltrate\infomation\子域名爆破\OneForAll-0.4.5\oneforall.py", line 16, in <module>
    from brute import Brute
  File "D:\infiltrate\infomation\子域名爆破\OneForAll-0.4.5\brute.py", line 14, in <module>
    import exrex
  File "D:\Python\Python311\Lib\site-packages\exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (D:\Python\Python311\Lib\re\__init__.py)
```

**预期结果**
```
NAME
    oneforall.py - OneForAll help summary page

SYNOPSIS
    oneforall.py - GROUP | COMMAND | VALUE

DESCRIPTION
    OneForAll is a powerful subdomain integration tool

    Example:
        python3 oneforall.py version
        python3 oneforall.py check
        python3 oneforall.py --target example.com run
        python3 oneforall.py --targets ./domains.txt run
        python3 oneforall.py --target example.com --alive False run
        python3 oneforall.py --target example.com --brute False run
        python3 oneforall.py --target example.com --port medium run
        python3 oneforall.py --target example.com --fmt csv run
        python3 oneforall.py --target example.com --dns False run
        python3 oneforall.py --target example.com --req False run
        python3 oneforall.py --target example.com --takeover False run
        python3 oneforall.py --target example.com --show True run

    Note:
        --port   small/medium/large  See details in ./config/setting.py(default small)
        --fmt csv/json (result format)
        --path   Result path (default None, automatically generated)

GROUPS
    GROUP is one of the following:

     data

     datas

     domains

COMMANDS
    COMMAND is one of the following:

     check
       Check if there is a new version and exit

     check_param
       Check parameter

     config_param
       Config parameter

     export_data
       Export data from the database

     main
       OneForAll main process

     run
       OneForAll running entrance

     version
       Print version information and exit

VALUES
    VALUE is one of the following:

     access_internet

     alive

     brute

     dns

     domain

     enable_wildcard

     fmt

     in_china

     path

     port

     req

     takeover

     target

     targets
```

**实际结果**
```
python311 .\oneforall.py
Traceback (most recent call last):
  File "D:\infiltrate\infomation\子域名爆破\OneForAll-0.4.5\oneforall.py", line 16, in <module>
    from brute import Brute
  File "D:\infiltrate\infomation\子域名爆破\OneForAll-0.4.5\brute.py", line 14, in <module>
    import exrex
  File "D:\Python\Python311\Lib\site-packages\exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (D:\Python\Python311\Lib\re\__init__.py)
```

**屏幕截图**
![image](https://user-images.githubusercontent.com/44149984/210911194-0cc2df97-3cd0-4d68-aa85-9fb7d4e4ac58.png)

**Comment by 939422744** [comment]
我也是

**Comment by FaithZSW** [comment]
我也是，有没有解决方案

**Comment by Talone123** [comment]
> 编辑 /../../site-packages/exrex.py
> 
> ```
> import sre_parse```
> ```

xx路径\site-packages\exrex.py
注释掉 site-packages\exrex.py
添加新行 import sre_parse

**Comment by JrDw0** [comment]
项目兼容最新版本python的成本较高，建议各位使用venv或者virtualenv的虚拟python环境来管理并使用多个python版本，或者通过docker使用。
