### ISSUE TITLE
ValueError: nameserver  is not an IP address or valid https URL

### ISSUE THREAD

**Issue by 2440012586** [shmilylty/OneForAll#294]
OneForAll is a powerful subdomain integration tool
             ___             _ _
 ___ ___ ___|  _|___ ___ ___| | | {v0.4.5 #dev}
| . |   | -_|  _| . |  _| .'| | |
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll is under development, please update before each use!

[*] Starting OneForAll @ 2023-01-29 16:10:06

16:10:06,807 [INFOR] utils:532 - Checking dependent environment
16:10:06,807 [INFOR] utils:544 - Checking network environment
16:10:07,026 [INFOR] utils:555 - Checking for the latest version
16:10:07,378 [INFOR] utils:579 - The current version v0.4.5 is already the latest version
16:10:07,379 [INFOR] oneforall:241 - Start running OneForAll
16:10:07,382 [INFOR] oneforall:246 - Got 1 domains
16:10:07,405 [INFOR] wildcard:108 - Detecting qq.com use wildcard dns record or not
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\dns\resolver.py", line 982, in nameservers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\desktop\tools\OneForAll-master\oneforall.py", line 275, in <module>
    fire.Fire(OneForAll)
  File "D:\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "F:\desktop\tools\OneForAll-master\oneforall.py", line 252, in run
    self.main()
  File "F:\desktop\tools\OneForAll-master\oneforall.py", line 155, in main
    self.enable_wildcard = wildcard.detect_wildcard(self.domain)
  File "F:\desktop\tools\OneForAll-master\modules\wildcard.py", line 119, in detect_wildcard
    is_enable = to_detect_wildcard(domain)
  File "F:\desktop\tools\OneForAll-master\modules\wildcard.py", line 110, in to_detect_wildcard
    if not all_resolve_success(random_subdomains):
  File "F:\desktop\tools\OneForAll-master\modules\wildcard.py", line 58, in all_resolve_success
    resolver = utils.dns_resolver()
  File "F:\desktop\tools\OneForAll-master\common\utils.py", line 374, in dns_resolver
    resolver = Resolver()
  File "D:\Python39\lib\site-packages\dns\resolver.py", line 756, in __init__
    self.read_registry()
  File "D:\Python39\lib\site-packages\dns\resolver.py", line 858, in read_registry
    self.nameservers = info.nameservers
  File "D:\Python39\lib\site-packages\dns\resolver.py", line 984, in nameservers
    raise ValueError(f'nameserver {nameserver} is not an '
ValueError: nameserver  is not an IP address or valid https URL

**Comment by JrDw0** [comment]
检查一下你的DNS解析设置，config目录下的default.py的resolver_nameservers

**Comment by freedomyj2019** [comment]
> 检查一下你的DNS解析设置，config目录下的 default.py 的resolver_nameservers

resolver_nameservers的配置如下，还是同样报错

# DNS解析设置
resolver_nameservers = [
    '223.5.5.5',  # AliDNS
    '119.29.29.29',  # DNSPod
    '114.114.114.114',  # 114DNS
    '8.8.8.8',  # Google DNS
    '1.1.1.1'  # CloudFlare DNS
]  # 指定查询的DNS域名服务器
resolver_timeout = 5.0  # 解析超时时间(默认5.0秒)
resolver_lifetime = 10.0  # 解析存活时间(默认10.0秒)
