### ISSUE TITLE
软件好像无法使用

### ISSUE THREAD

**Issue by zhaimuyanxian** [shmilylty/OneForAll#311]
**是否使用了最新代码**
是
**Bug描述**
OneForAll-0.4.5无法使用
**运行环境**
 - 系统：
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.1
Codename:       kali-rolling
 - Python版本：
Python 3.11.2
 - OneForAll版本：
OneForAll-0.4.5
 
**如何复现**
复现步骤（选写）
使用程序时无法使用
复现命令（必写）
python3 oneforall.py -h    
复制完整的报错文本（必写）
Traceback (most recent call last):
  File "/root/桌面/OneForAll-0.4.5/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/桌面/OneForAll-0.4.5/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![1](https://user-images.githubusercontent.com/46186761/233430344-f1faa564-812d-4c7d-9c07-3707c9c27e07.png)
![2](https://user-images.githubusercontent.com/46186761/233430563-217aa32f-ab4a-45a6-920e-866b05e16b56.png)
![3](https://user-images.githubusercontent.com/46186761/233430604-b9e28cec-40d4-4c48-bb93-d008a7a7842d.png)
![4](https://user-images.githubusercontent.com/46186761/233431741-e746a148-e856-4285-bad3-b7f8fbaa878c.png)

**Comment by nuanfeng1yue** [comment]
解决了吗，一样的问题

**Comment by dtxharry** [comment]
一样,不行
