### ISSUE TITLE
Mac OS 无法使用

### ISSUE THREAD

**Issue by EmptyZeroRain** [shmilylty/OneForAll#317]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
 是
**Bug描述**
清晰而简洁的Bug描述（必写）

安装了pip 库 执行ba报错

**运行环境**
 - 系统：MAC OS 12.6.5
 - Python版本：Python 3.11.3
 - OneForAll版本：0.4.5
 
**如何复现**
复现步骤（选写）

复现命令（必写）
执行 python3 oneforall.py --help  报错

**报错文本**
复制完整的报错文本（必写）

Traceback (most recent call last):
  File "/Users/rain/.tools/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/Users/rain/.tools/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/site-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

 正常情况 应该是直接提示help 

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

库报错

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
<img width="906" alt="image" src="https://github.com/shmilylty/OneForAll/assets/48972652/d2a07592-4e17-48f7-9e8a-1b60a457cae6">

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by moeuuki** [comment]
```bash
> brew install python@3.10
> brew unlink python@3.11
> python3 -m pip install -r requirements.txt
> python3 oneforall.py -help
```

**Comment by XingXiaoWu** [comment]
```
cd OneForAll/
python3.10 -m venv venv
source venv/bin/activate
python3 -m pip install -U pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/
pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
python3 oneforall.py --help
```

**Comment by peterzyk** [comment]
pip uninstall exrex
pip install exrex

即可
