### ISSUE TITLE
出现了不存在的模块，即使已经安装好了

### ISSUE THREAD

**Issue by vFREE-1** [shmilylty/OneForAll#325]
**是否使用了最新代码**
是
**Bug描述**
提示re的模块ste_parse不存在，用的是python3的环境，且re已经存在；

**运行环境**
 - 系统：[Windows 10 x64]（必写）
 - Python版本：[3.11. 1]（必写）
 - OneForAll版本：[z]（最新的）
 
**如何复现**
复现步骤（选写）
python3 oneforall.py xxxxxxxxxx

复现命令（必写）

**报错文本**
Traceback (most recent call last):
  File "C:\Users\WIN10\Desktop\信息收集\OneForAll-master\oneforall.py", line 16, in <module>
    from brute import Brute
  File "C:\Users\WIN10\Desktop\信息收集\OneForAll-master\brute.py", line 14, in <module>
    import exrex
  File "C:\vFREE\python3\Lib\site-packages\exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (C:\vFREE\python3\Lib\re\__init__.py)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by wNodi** [comment]
修改exrex.py文件，将from re import sre_parse, U改成import sre_parse

**Comment by 17moonup** [comment]
補充一下

**Comment by 17moonup** [comment]
補充一下，將exrex.py中的from re import sre_parse, U 改爲import parse加上from re import U

**Comment by Asxjdb** [comment]
在这个路径下面：/home/kali/.local/lib/python3.11/site-packages/exrex.py
