### ISSUE TITLE
Docker镜像运行出错

### ISSUE THREAD

**Issue by Dylan-Li8** [shmilylty/OneForAll#330]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）

**Bug描述**
执行docker运行容器后提示：
```
docker run -it --rm -v ~/results:/OneForAll/results -v ~/.config:/OneForAll/config shmilylty/oneforall --target 58.com run
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
ModuleNotFoundError: No module named 'config.log'
```

**运行环境**
 - 系统：CentOS 7
 - Python版本：Docker
 - OneForAll版本：最新Docker镜像
 
**报错文本**
```
docker run -it --rm -v ~/results:/OneForAll/results -v ~/.config:/OneForAll/config shmilylty/oneforall --target job5156.com run
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
ModuleNotFoundError: No module named 'config.log'
```

**Comment by cornradio** [comment]
同样错误 
我这里

**Comment by blackdoufu53-wq** [comment]
师傅解决了吗？

**Comment by 2005ab3** [comment]
解决了，oneforall功能太强了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年12月5日(周五) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [shmilylty/OneForAll] Docker镜像运行出错 (Issue #330)


blackdoufu53-wq left a comment (shmilylty/OneForAll#330)
 
师傅解决了吗？
