### ISSUE TITLE
无法解析域名

### ISSUE THREAD

**Issue by pyubun** [shmilylty/OneForAll#336]
**是否使用了最新代码**
是

**Bug描述**
无法解析域名
ValueError: nameserver ; is not an IP address or valid https URL

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.8.5
 - OneForAll版本：0.4.5
 
**如何复现**
复现步骤（选写）

python oneforall.py --target baidu.com run

**报错文本**
[*] Starting OneForAll @ 2023-08-07 10:50:56

10:50:56,284 [INFOR] utils:523 - Checking dependent environment
10:50:56,284 [INFOR] utils:535 - Checking network environment
10:51:04,287 [INFOR] utils:546 - Checking for the latest version
10:51:05,694 [INFOR] utils:570 - The current version v0.4.5 is already the latest version
10:51:05,696 [INFOR] oneforall:243 - Start running OneForAll
10:51:05,698 [INFOR] oneforall:248 - Got 1 domains
10:51:05,725 [INFOR] wildcard:108 - Detecting baidu.com use wildcard dns record or not
Traceback (most recent call last):
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\dns\resolver.py", line 982, in nameservers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oneforall.py", line 277, in <module>
    fire.Fire(OneForAll)
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 254, in run
    self.main()
  File "oneforall.py", line 156, in main
    self.enable_wildcard = wildcard.detect_wildcard(self.domain)
  File "C:\Users\Hasee\Downloads\OneForAll-0.4.5\OneForAll-0.4.5\modules\wildcard.py", line 119, in detect_wildcard
    is_enable = to_detect_wildcard(domain)
  File "C:\Users\Hasee\Downloads\OneForAll-0.4.5\OneForAll-0.4.5\modules\wildcard.py", line 110, in to_detect_wildcard
    if not all_resolve_success(random_subdomains):
  File "C:\Users\Hasee\Downloads\OneForAll-0.4.5\OneForAll-0.4.5\modules\wildcard.py", line 58, in all_resolve_success
    resolver = utils.dns_resolver()
  File "C:\Users\Hasee\Downloads\OneForAll-0.4.5\OneForAll-0.4.5\common\utils.py", line 372, in dns_resolver
    resolver = Resolver()
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\dns\resolver.py", line 756, in __init__
    self.read_registry()
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\dns\resolver.py", line 858, in read_registry
    self.nameservers = info.nameservers
  File "C:\Users\Hasee\AppData\Local\Programs\Python\Python38\lib\site-packages\dns\resolver.py", line 984, in nameservers
    raise ValueError(f'nameserver {nameserver} is not an '
ValueError: nameserver ; is not an IP address or valid https URL

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**

![image](https://github.com/shmilylty/OneForAll/assets/56460010/486466ea-4bc6-41e2-976b-06f72f310d0e)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by tcyba** [comment]
解决问题了码

**Comment by jangzemin** [comment]
pip install dnspython==2.1.0解决

**Comment by tcyba** [comment]
thank you!




Upload
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shmilylty/OneForAll"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月27日(星期二) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shmilylty/OneForAll] 无法解析域名 (Issue #336)





 
pip install dnspython==2.1.0解决

**Comment by JrDw0** [comment]
感谢回答

**Comment by Niu-zida** [comment]
@jangzemin Thanks for the answer！
