### ISSUE TITLE
请填写BUG标题

### ISSUE THREAD

**Issue by account-2-Eason** [shmilylty/OneForAll#342]
Traceback (most recent call last):
  File "/root/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Comment by JrDw0** [comment]
可能需要使用venv或pip配置独立的python3.8环境使用
