### ISSUE TITLE
请填写BUG标题

### ISSUE THREAD

**Issue by Endinc** [shmilylty/OneForAll#343]
**是否使用了最新代码**
是

**Bug描述**
清晰而简洁的Bug描述（必写）

**运行环境**
 - 系统：Windows 11 x64（必写）
 - Python版本： 3.8.0（必写）
 - OneForAll版本:0.4.5（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
'E:\wangan\Penetration' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
12:11:49,714Traceback (most recent call last):
 [  File "oneforall.py", line 277, in <module>
INFOR    ] fire.Fire(OneForAll)brute
:  File "E:\Python38\lib\site-packages\fire\core.py", line 141, in Fire
197     - component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
Counting IP cname appear times
component, remaining_args = _CallAndUpdateTrace(
  File "E:\Python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 254, in run
    self.main()
  File "oneforall.py", line 171, in main
    brute.run()
  File "E:\wangan\Penetration testing\Information Collection\OneForAll-0.4.5\brute.py", line 473, in run
    valid_subdomains = self.main(self.domain)
  File "E:\wangan\Penetration testing\Information Collection\OneForAll-0.4.5\brute.py", line 446, in main
    appear_times = stat_appear_times(output_path)
  File "E:\wangan\Penetration testing\Information Collection\OneForAll-0.4.5\brute.py", line 200, in stat_appear_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\wangan\\Penetration testing\\Information Collection\\OneForAll-0.4.5\\results\\temp\\resolved_result_tyu.edu.cn_20230825_121149.json'

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
![image](https://github.com/shmilylty/OneForAll/assets/142462909/1f61dacf-2b28-4ef9-bc18-b6335c130cbb)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by JrDw0** [comment]
看起来是路径中带了空格导致的问题
