### ISSUE TITLE
i can't finish installation

### ISSUE THREAD

**Issue by Hamada104** [shmilylty/OneForAll#344]
**Whether the latest code is used**
Yes 
**Bug description**
Clear and concise Bug description(required)
Traceback (most recent call last):
  File "/root/tools/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/tools/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Operation environment**
 - System information: [kali 3.2023] (required)
 - Python version: [Python 3.11.4] (required)
 - OneForAll version: [[v0.4.5] (required)
 
**How to reproduce**
1. Step (optional)

2. Command (python3 oneforall.py --help)

**Error text**
Traceback (most recent call last):
  File "/root/tools/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/tools/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Expected results**
A clear and concise description of the expected results (optional, such as what a normal situation should look like)

**Actual results**
A clear and concise description of the actual results (optional, such as any errors)

**Screenshot**
Screenshot of complete OneForAll execution process (recommended upload)

**Log upload**
Upload oneforall.log files (it is recommended to upload logs in case of complex problems)

**Supplementary information**
Some other supplementary notes about bug

**Comment by dt022** [comment]
I got the same issue and fixed it by doing the following:

- Open the exrex.py (in your case it's located **/usr/local/lib/python3.11/dist-packages/exrex.py**)
- Change line 25 `from re import sre_parse, U` to:
```
import sre_parse
from re import U
```
