### ISSUE TITLE
报错提示Traceback (most recent call last):   File "D:\Python38-32\lib\site-packages\dns\resolver.py", line 982, in nameservers     raise NotImplementedError NotImplementedError

### ISSUE THREAD

**Issue by ihmod** [shmilylty/OneForAll#351]
**是否使用了最新代码**
是 v0.4.5
**Bug描述**

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：已尝试 3.10.7、3.11.0、3.6.0 、3.8.0
 - OneForAll版本：0.4.5
 
**如何复现**
全新的python
pip版本更到最新
安装依赖，全部成功
执行单个域名查询命令
报错

复现命令   python oneforall.py --target baidu.com run

**报错文本**
06:56:48,346 [INFOR] utils:532 - Checking dependent environment
06:56:48,346 [INFOR] utils:544 - Checking network environment
06:56:48,963 [INFOR] utils:555 - Checking for the latest version
06:56:49,776 [INFOR] utils:579 - The current version v0.4.5 is already the latest version
06:56:49,776 [INFOR] oneforall:241 - Start running OneForAll
06:56:49,776 [INFOR] oneforall:246 - Got 1 domains
06:56:49,807 [INFOR] wildcard:108 - Detecting baidu.com use wildcard dns record or not
Traceback (most recent call last):
  File "D:\Python38-32\lib\site-packages\dns\resolver.py", line 982, in nameservers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oneforall.py", line 275, in <module>
    fire.Fire(OneForAll)
  File "D:\Python38-32\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Python38-32\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Python38-32\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 252, in run
    self.main()
  File "oneforall.py", line 155, in main
    self.enable_wildcard = wildcard.detect_wildcard(self.domain)
  File "D:\OneForAll\modules\wildcard.py", line 119, in detect_wildcard
    is_enable = to_detect_wildcard(domain)
  File "D:\OneForAll\modules\wildcard.py", line 110, in to_detect_wildcard
    if not all_resolve_success(random_subdomains):
  File "D:\OneForAll\modules\wildcard.py", line 58, in all_resolve_success
    resolver = utils.dns_resolver()
  File "D:\OneForAll\common\utils.py", line 374, in dns_resolver
    resolver = Resolver()
  File "D:\Python38-32\lib\site-packages\dns\resolver.py", line 756, in __init__
    self.read_registry()
  File "D:\Python38-32\lib\site-packages\dns\resolver.py", line 858, in read_registry
    self.nameservers = info.nameservers
  File "D:\Python38-32\lib\site-packages\dns\resolver.py", line 984, in nameservers
    raise ValueError(f'nameserver {nameserver} is not an '
ValueError: nameserver ; is not an IP address or valid https URL

**预期结果**
正常应该进行探测生成子域名表格

**实际结果**
提示好几个模块报错，尝试卸载dnspython 、fire模块重新安装，还是会报错

**屏幕截图**
python版本
![image](https://github.com/shmilylty/OneForAll/assets/80114982/d06609a7-2e14-47e7-8405-6461ac82ec2a)
依赖情况
![image](https://github.com/shmilylty/OneForAll/assets/80114982/47f3ce34-3a14-4eac-a613-906bb910367d)
报错命令
![image](https://github.com/shmilylty/OneForAll/assets/80114982/fee2e825-80a8-4d18-a79d-50ab6ed913a3)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
以为是安装包的影响，尝试为项目创建虚拟python环境并重新下载所有依赖，还是报一样的错
尝试重新安装python，3.11.0（提示fire模块）, 3.6.0（pip无法更新到23.2.1），3.8.0（和3.10.7报一样的错）

**Comment by ihmod** [comment]
**这是oneforall.log的全部内容**
2023-09-10 06:50:04,893 [DEBUG] MainProcess(17080):MainThread        (15448) | oneforall.run:235 - Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
2023-09-10 06:50:04,893 [DEBUG] MainProcess(17080):MainThread        (15448) | oneforall.run:236 - OneForAll v0.4.5
2023-09-10 06:50:04,893 [INFOR] MainProcess(17080):MainThread        (15448) | utils.check_dep:532 - Checking dependent environment
2023-09-10 06:50:04,893 [INFOR] MainProcess(17080):MainThread        (15448) | utils.get_net_env:544 - Checking network environment
2023-09-10 06:50:04,893 [DEBUG] MainProcess(17080):MainThread        (15448) | utils.check_net:507 - Trying to access https://www.baidu.com
2023-09-10 06:50:05,454 [DEBUG] MainProcess(17080):MainThread        (15448) | utils.check_net:524 - Access to Internet OK
2023-09-10 06:50:05,454 [INFOR] MainProcess(17080):MainThread        (15448) | utils.check_version:555 - Checking for the latest version
2023-09-10 06:50:05,913 [INFOR] MainProcess(17080):MainThread        (15448) | utils.check_version:579 - The current version v0.4.5 is already the latest version
2023-09-10 06:50:05,913 [INFOR] MainProcess(17080):MainThread        (15448) | oneforall.run:241 - Start running OneForAll
2023-09-10 06:50:05,913 [DEBUG] MainProcess(17080):MainThread        (15448) | utils.get_domains:160 - Getting domains
2023-09-10 06:50:05,930 [DEBUG] MainProcess(17080):MainThread        (15448) | utils.get_domains:168 - The obtained domains 
['hnie.edu.cn']
2023-09-10 06:50:05,930 [INFOR] MainProcess(17080):MainThread        (15448) | oneforall.run:246 - Got 1 domains
2023-09-10 06:50:05,948 [INFOR] MainProcess(17080):MainThread        (15448) | wildcard.to_detect_wildcard:108 - Detecting hnie.edu.cn use wildcard dns record or not
2023-09-10 06:50:54,453 [DEBUG] MainProcess(16848):MainThread        (14364) | oneforall.run:235 - Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
2023-09-10 06:50:54,453 [DEBUG] MainProcess(16848):MainThread        (14364) | oneforall.run:236 - OneForAll v0.4.5
2023-09-10 06:50:54,453 [INFOR] MainProcess(16848):MainThread        (14364) | utils.check_dep:532 - Checking dependent environment
2023-09-10 06:50:54,453 [INFOR] MainProcess(16848):MainThread        (14364) | utils.get_net_env:544 - Checking network environment
2023-09-10 06:50:54,453 [DEBUG] MainProcess(16848):MainThread        (14364) | utils.check_net:507 - Trying to access https://www.amazon.com/
2023-09-10 06:50:54,960 [DEBUG] MainProcess(16848):MainThread        (14364) | utils.check_net:524 - Access to Internet OK
2023-09-10 06:50:54,962 [INFOR] MainProcess(16848):MainThread        (14364) | utils.check_version:555 - Checking for the latest version
2023-09-10 06:50:55,438 [INFOR] MainProcess(16848):MainThread        (14364) | utils.check_version:579 - The current version v0.4.5 is already the latest version
2023-09-10 06:50:55,438 [INFOR] MainProcess(16848):MainThread        (14364) | oneforall.run:241 - Start running OneForAll
2023-09-10 06:50:55,438 [DEBUG] MainProcess(16848):MainThread        (14364) | utils.get_domains:160 - Getting domains
2023-09-10 06:50:55,438 [DEBUG] MainProcess(16848):MainThread        (14364) | utils.get_domains:168 - The obtained domains 
['baidu.com']
2023-09-10 06:50:55,438 [INFOR] MainProcess(16848):MainThread        (14364) | oneforall.run:246 - Got 1 domains
2023-09-10 06:50:55,455 [INFOR] MainProcess(16848):MainThread        (14364) | wildcard.to_detect_wildcard:108 - Detecting baidu.com use wildcard dns record or not
2023-09-10 06:56:48,346 [DEBUG] MainProcess(8664):MainThread        (17588) | oneforall.run:235 - Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
2023-09-10 06:56:48,346 [DEBUG] MainProcess(8664):MainThread        (17588) | oneforall.run:236 - OneForAll v0.4.5
2023-09-10 06:56:48,346 [INFOR] MainProcess(8664):MainThread        (17588) | utils.check_dep:532 - Checking dependent environment
2023-09-10 06:56:48,346 [INFOR] MainProcess(8664):MainThread        (17588) | utils.get_net_env:544 - Checking network environment
2023-09-10 06:56:48,346 [DEBUG] MainProcess(8664):MainThread        (17588) | utils.check_net:507 - Trying to access https://www.bing.com
2023-09-10 06:56:48,963 [DEBUG] MainProcess(8664):MainThread        (17588) | utils.check_net:524 - Access to Internet OK
2023-09-10 06:56:48,963 [INFOR] MainProcess(8664):MainThread        (17588) | utils.check_version:555 - Checking for the latest version
2023-09-10 06:56:49,776 [INFOR] MainProcess(8664):MainThread        (17588) | utils.check_version:579 - The current version v0.4.5 is already the latest version
2023-09-10 06:56:49,776 [INFOR] MainProcess(8664):MainThread        (17588) | oneforall.run:241 - Start running OneForAll
2023-09-10 06:56:49,776 [DEBUG] MainProcess(8664):MainThread        (17588) | utils.get_domains:160 - Getting domains
2023-09-10 06:56:49,776 [DEBUG] MainProcess(8664):MainThread        (17588) | utils.get_domains:168 - The obtained domains 
['baidu.com']
2023-09-10 06:56:49,776 [INFOR] MainProcess(8664):MainThread        (17588) | oneforall.run:246 - Got 1 domains
2023-09-10 06:56:49,807 [INFOR] MainProcess(8664):MainThread        (17588) | wildcard.to_detect_wildcard:108 - Detecting baidu.com use wildcard dns record or not
2023-09-10 07:08:50,616 [DEBUG] MainProcess(19480):MainThread        (19748) | oneforall.run:235 - Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
2023-09-10 07:08:50,616 [DEBUG] MainProcess(19480):MainThread        (19748) | oneforall.run:236 - OneForAll v0.4.5
2023-09-10 07:08:50,616 [INFOR] MainProcess(19480):MainThread        (19748) | utils.check_dep:532 - Checking dependent environment
2023-09-10 07:08:50,616 [INFOR] MainProcess(19480):MainThread        (19748) | utils.get_net_env:544 - Checking network environment
2023-09-10 07:08:50,616 [DEBUG] MainProcess(19480):MainThread        (19748) | utils.check_net:507 - Trying to access https://www.baidu.com
2023-09-10 07:08:50,782 [DEBUG] MainProcess(19480):MainThread        (19748) | utils.check_net:524 - Access to Internet OK
2023-09-10 07:08:50,784 [INFOR] MainProcess(19480):MainThread        (19748) | utils.check_version:555 - Checking for the latest version
2023-09-10 07:08:51,116 [INFOR] MainProcess(19480):MainThread        (19748) | utils.check_version:579 - The current version v0.4.5 is already the latest version
2023-09-10 07:08:51,122 [INFOR] MainProcess(19480):MainThread        (19748) | oneforall.run:241 - Start running OneForAll
2023-09-10 07:08:51,122 [DEBUG] MainProcess(19480):MainThread        (19748) | utils.get_domains:160 - Getting domains
2023-09-10 07:08:51,123 [DEBUG] MainProcess(19480):MainThread        (19748) | utils.get_domains:168 - The obtained domains 
['baidu.com']
2023-09-10 07:08:51,123 [INFOR] MainProcess(19480):MainThread        (19748) | oneforall.run:246 - Got 1 domains
2023-09-10 07:08:51,150 [INFOR] MainProcess(19480):MainThread        (19748) | wildcard.to_detect_wildcard:108 - Detecting baidu.com use wildcard dns record or not

**Comment by tcyba** [comment]
一样问题，昨天还能用，今天怎么用不了了

**Comment by excuses0217** [comment]
一样的问题，前段时间还能用，现在用不了了

**Comment by 666587** [comment]
太感谢了搞了好久
