### ISSUE TITLE
3.12不支持，No module named 'distutils'

### ISSUE THREAD

**Issue by buyaoyongroot** [shmilylty/OneForAll#357]
**是否使用了最新代码**
是

**Bug描述**
(one) C:\Users\JM\Desktop\OneForAll-0.4.5>python oneforall.py -target baidu.com run
Traceback (most recent call last):
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\oneforall.py", line 15, in <module>
    import export
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\export.py", line 13, in <module>
    from common import utils
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\common\utils.py", line 13, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

随着Python 3.12的发布，distutils终于被移除。根据 PEP 632，distutils 在 Python 3.10 中被标记为废弃，在 Python 3.12 中将不再是标准库的一部分。从distutils中导入将导致一个错误，因为不会有向后兼容的情况出现

**运行环境**
 - 系统：[win10]（必写）
 - Python版本：[3.12]（必写）
 - OneForAll版本：[0.4.5]（必写）
 
**如何复现**
不兼容3.12

复现命令（必写）
python oneforall.py -target baidu.com run

**报错文本**
(one) C:\Users\JM\Desktop\OneForAll-0.4.5>python oneforall.py -target baidu.com run
Traceback (most recent call last):
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\oneforall.py", line 15, in <module>
    import export
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\export.py", line 13, in <module>
    from common import utils
  File "C:\Users\JM\Desktop\OneForAll-0.4.5\common\utils.py", line 13, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**预期结果**
正常运行

**实际结果**
ModuleNotFoundError: No module named 'distutils'

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by maple67** [comment]
这个怎么操作的

**Comment by maple67** [comment]
3.12,亲测成功

**Comment by lishixin7777** [comment]
我也是失败

**Comment by m4ra7h0n** [comment]
pip install setuptools
pip uninstall exrex
pip install exrex

**Comment by JrDw0** [comment]
建议使用venv或者pipenv的独立python3.6环境安装
