### ISSUE TITLE
Please fill in the BUG module errors after sucessful installtitle

### ISSUE THREAD

**Issue by cybermatrixza** [shmilylty/OneForAll#363]
iam geting the following erroors after installing in vps

└─$ python3 oneforall.py --help
Traceback (most recent call last):
  File "/home/bugspiderlee/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/home/bugspiderlee/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/home/bugspiderlee/.local/lib/python3.11/site-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Comment by ZhangXueZe** [comment]
i have the same bug

**Comment by Indian-vikram** [comment]
I have the same bug

**Comment by badhacker0x1** [comment]
facing the same issue with python version 3.11

**Comment by mdashik123456** [comment]
same issue with python 3.11

**Comment by Garte153sa** [comment]
same

**Comment by dharmesh1898** [comment]
Anyone Found solution to this? i'm facing the same error....

**Comment by apmcspatidar** [comment]
i have a same bug

**Comment by supercyber1** [comment]
Getting same bug any help would be appreciated.

**Comment by Garte153sa** [comment]
I think this woul help you out this helped me . 
"pip install --upgrade exrex"

**Comment by Garte153sa** [comment]
And a new error came module treelib
pip3 install treelib would do all rest

**Comment by whatsdd** [comment]
> pip install --upgrade exrex

This works, many thanks
@shmilylty

**Comment by loststars6517** [comment]
> I think this woul help you out this helped me . "pip install --upgrade exrex"

work!

**Comment by kurogai** [comment]
> I think this woul help you out this helped me . "pip install --upgrade exrex"

Works!!! Thank you

**Comment by aksa06** [comment]
> I think this woul help you out this helped me . "pip install --upgrade exrex"

Thanks, my issue was resolved after "pip install --upgrade exrex"

**Comment by Hammad203-code** [comment]
"pip install --upgrade exrex" this is not working on my kali
