### ISSUE TITLE
安装了库还是报错

### ISSUE THREAD

**Issue by websecer** [shmilylty/OneForAll#371]
```
Traceback (most recent call last):
  File "/home/roman/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/home/roman/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/home/roman/OneForAll/oneforall/lib/python3.11/site-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

```

**Comment by 41an** [comment]
pip uninstall exrex
pip install exrex

**Comment by 41an** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/roman/OneForAll/oneforall.py", line 16, in <module>
>     from brute import Brute
>   File "/home/roman/OneForAll/brute.py", line 14, in <module>
>     import exrex
>   File "/home/roman/OneForAll/oneforall/lib/python3.11/site-packages/exrex.py", line 25, in <module>
>     from re import sre_parse, U
> ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)
> ```
pip uninstall exrex
pip install exrex
