### ISSUE TITLE
安装依赖问题 

### ISSUE THREAD

**Issue by JackeyLov5** [shmilylty/OneForAll#372]
3.6和3.9 都试了
➜  OneForAll git:(master) python3 --version
Python 3.6.8
➜  OneForAll git:(master) python3 oneforall.py --target baidu.com run
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import export
  File "/root/tools/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/root/tools/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/root/tools/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/root/tools/OneForAll/config/log.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
➜  OneForAll git:(master) pip3 install -r requirements.txt 
Collecting beautifulsoup4==4.11.1
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting certifi==2022.06.15
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting chardet==5.0.0
  Using cached chardet-5.0.0-py3-none-any.whl (193 kB)
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: dnspython==2.2.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (2.2.1)
Collecting exrex==0.10.5
  Using cached exrex-0.10.5.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... done
Collecting fire==0.4.0
  Using cached fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... done
Collecting future==0.18.2
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... done
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting loguru==0.6.0
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting PySocks==1.7.1
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement requests==2.28.1 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1)
ERROR: No matching distribution found for requests==2.28.1

**Comment by gcz12** [comment]
我也是这样，请问解决了吗

**Comment by gcz12** [comment]
> > 我也是这样，请问解决了吗
> 
> 改一下配置里的版本。好像也可以运行。要么就安装python3.10

请问怎么改配置里的版本啊

**Comment by kcime** [comment]
下载python3.10的安装程序，修改环境变量就可以了
下载链接：https://www.python.org/downloads/release/python-3100/

**Comment by CN-Hutian** [comment]
我是把python环境全删了 ，然后只安装一个python38版本即可解决
