### ISSUE TITLE
No such file or directory 运行找不到文件

### ISSUE THREAD

**Issue by 41an** [shmilylty/OneForAll#374]
**Bug描述**
python3 ./oneforall.py --target x.com run会提示找不文件

**运行环境**
 - 系统：kali arm64
 - Python版本：3.11.8
 - OneForAll版本：0.4.5
 
**如下是报错信息**
```shell
Traceback (most recent call last):
  File "/root/tools/OneForAll/./oneforall.py", line 275, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/OneForAll/./oneforall.py", line 252, in run
    self.main()
  File "/root/tools/OneForAll/./oneforall.py", line 182, in main
    self.data = resolve.run_resolve(self.domain, self.data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/OneForAll/common/resolve.py", line 152, in run_resolve
    massdns_path = utils.get_massdns_path(massdns_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/OneForAll/common/utils.py", line 624, in get_massdns_path
    path.chmod(S_IXUSR)
  File "/usr/lib/python3.11/pathlib.py", line 1133, in chmod
    os.chmod(self, mode, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/root/tools/OneForAll/thirdparty/massdns/massdns_linux_aarch64'
```

**Comment by symor** [comment]
同问 解决了么
