### ISSUE TITLE
fire module problem

### ISSUE THREAD

**Issue by lakshayji123** [shmilylty/OneForAll#382]
Traceback (most recent call last):
  File "/root/OneForAll/oneforall.py", line 11, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

**Comment by anjan123427** [comment]
same problem 
Traceback (most recent call last):
  File "/home/kali/OneForAll/./oneforall.py", line 16, in <module>
    from brute import Brute
  File "/home/kali/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Comment by CrazyBhai8** [comment]
Try this:-
pip install fire 
command

and install all the packets which needs to oneforall.

**Comment by Techy297** [comment]
it,s Helpful , Thanks

**Comment by SUBRAMANYAMRAJU06** [comment]
Collecting fire==0.4.0
  Downloading fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  
  how can i solve this can anyone help me

**Comment by KaledKelevra** [comment]
Still no solution to this error? 😓

**Comment by suryadi1111** [comment]
![hsdtgf](https://github.com/user-attachments/assets/433e295a-21e6-4ca1-9639-40f91ed25e76)

**Comment by diaoqi129** [comment]
> Collecting fire==0.4.0 Downloading fire-0.4.0.tar.gz (87 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1
> 
> how can i solve this can anyone help me

i have met the same question ,have u fix it ?

**Comment by seopalsandhu1-byte** [comment]
Traceback (most recent call last):
  File "/root/OneForAll/oneforall.py", line 11, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
                                               please tell me the solution of this immediately
