### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by devilhi** [shmilylty/OneForAll#383]
Traceback (most recent call last):
  File "/home/hacker/Desktop/OneForAll/oneforall.py", line 11, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

**Comment by SourinMondal1** [comment]
> Traceback (most recent call last): File "/home/hacker/Desktop/OneForAll/oneforall.py", line 11, in import fire ModuleNotFoundError: No module named 'fire'

**Comment by trumpsandhu1-blip** [comment]
same problem i will also see please help me
