### ISSUE TITLE
无法生成文件以及批量扫描

### ISSUE THREAD

**Issue by ggforlove** [shmilylty/OneForAll#384]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
无法保存结果成一个正常的表
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）windows10 行4
 - Python版本：[例如3.7.1]（必写）3.8.2
 - OneForAll版本：[例如0.3.0]（必写）最新
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）
'D:\web' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
19:10:00,713 [INFOR] brute:197 - Counting IP cname appear times
Traceback (most recent call last):
  File ".\oneforall.py", line 275, in <module>
    fire.Fire(OneForAll)
  File "D:\python\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\python\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\python\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File ".\oneforall.py", line 252, in run
    self.main()
  File ".\oneforall.py", line 169, in main
    brute.run()
  File "D:\web hack\OneForAll\OneForAll\brute.py", line 470, in run
    valid_subdomains = self.main(self.domain)
  File "D:\web hack\OneForAll\OneForAll\brute.py", line 445, in main
    appear_times = stat_appear_times(output_path)
  File "D:\web hack\OneForAll\OneForAll\brute.py", line 200, in stat_appear_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\web hack\\OneForAll\\OneForAll\\results\\temp\\resolved_result_duxiaoman.com_20240618_191000.json'
**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by academic-cat95** [comment]
我也是这种情况，massdns在指定的路径下，但是就指向其他路径了。
反馈报错信息。
16:05:30,442 [INFOR] brute:441 - Running massdns to brute subdomains
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
16:05:30,449 [Traceback (most recent call last):
  File "D:\Program Files (x86)\Securityservice\xxx\OneForAll-master\oneforall.py", line 275, in <module>
INFOR    ] fire.Fire(OneForAll)brute
:  File "C:\Python\Lib\site-packages\fire\core.py", line 141, in Fire
197 -     component_trace = _Fire(component, args, parsed_flag_args, context, name)Counting IP cname appear times

**Comment by symor** [comment]
我也遇到了
Traceback (most recent call last):
  File "oneforall.py", line 275, in <module>
    fire.Fire(OneForAll)
  File "/home/symor/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/symor/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/symor/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 252, in run
    self.main()
  File "oneforall.py", line 169, in main
    brute.run()
  File "/data/tools/OneForAll/brute.py", line 470, in run
    valid_subdomains = self.main(self.domain)
  File "/data/tools/OneForAll/brute.py", line 445, in main
    appear_times = stat_appear_times(output_path)
  File "/data/tools/OneForAll/brute.py", line 200, in stat_appear_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/data/tools/OneForAll/results/temp/resolved_result_hawxyc.com_20250207_090906.json'



好像也是utils.call_massdns(massdns_path, dict_path, ns_path, output_path,
                           log_path, quiet_mode=self.quite,
                           concurrent_num=self.concurrent_num)这个函数没成功创建文件
