### ISSUE TITLE
moduleNotFound error

### ISSUE THREAD

**Issue by g1-art** [shmilylty/OneForAll#388]
**i am using command python3 oneforall.py -h and it shows me,**

Traceback (most recent call last):
  File "/home/situ/Desktop/OneForAll/oneforall.py", line 15, in <module>
    import export
  File "/home/situ/Desktop/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/home/situ/Desktop/OneForAll/common/utils.py", line 18, in <module>
    import tenacity
ModuleNotFoundError: No module named 'tenacity'

i am using,
linux amd64
python version 3.11.8
oneForAll version  v0.4.5

Traceback (most recent call last):
  File "/home/situ/Desktop/OneForAll/oneforall.py", line 15, in <module>
    import export
  File "/home/situ/Desktop/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/home/situ/Desktop/OneForAll/common/utils.py", line 18, in <module>
    import tenacity
ModuleNotFoundError: No module named 'tenacity'

![Screenshot 2024-07-06 102853](https://github.com/shmilylty/OneForAll/assets/157264435/66ba5720-adcd-4255-84c8-2ebfeb60983d)

**Comment by hetvaishnav1106** [comment]
what is solution for this error

**Comment by g1-art** [comment]
@hetvaishnav1106 it is a bug

**Comment by trumpsandhu1-blip** [comment]
─# python3 oneforall.py -h
Traceback (most recent call last):
  File "/root/OneForAll/oneforall.py", line 11, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
                                                  please help me friends
