### ISSUE TITLE
tool not running traceback issue 

### ISSUE THREAD

**Issue by chirag9718** [shmilylty/OneForAll#392]
**python3 oneforall.py --help**

Traceback (most recent call last):
  File "/root/tools/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/tools/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

when running the above command getting this.

**Comment by Vekvi-BugHunter** [comment]
I had the same problem, but I was able to resolve it by doing this:

1) In your case, the file is located at /usr/local/lib/python3.11/dist-packages/exrex.py. Open it.

`mousepad   /usr/local/lib/python3.11/dist-packages/exrex.py`

2)Replace "re import sre_parse, U" on line 25 with:
```

import sre_parse
from re import U
```

**Comment by paneendar** [comment]
Try  

pip3 install --upgrade --force-reinstall exrex

**Comment by Walidhossain010** [comment]
> I had the same problem, but I was able to resolve it by doing this:
> 
> 1. In your case, the file is located at /usr/local/lib/python3.11/dist-packages/exrex.py. Open it.
> 
> `mousepad /usr/local/lib/python3.11/dist-packages/exrex.py`
> 
> 2)Replace "re import sre_parse, U" on line 25 with:
> 
> ```
> 
> import sre_parse
> from re import U
> ```

thanks. it worked

**Comment by brokeitguyio** [comment]
> > I had the same problem, but I was able to resolve it by doing this:
> > 
> > 1. In your case, the file is located at /usr/local/lib/python3.11/dist-packages/exrex.py. Open it.
> > 
> > `mousepad /usr/local/lib/python3.11/dist-packages/exrex.py`
> > 2)Replace "re import sre_parse, U" on line 25 with:
> > ```
> > 
> > import sre_parse
> > from re import U
> > ```
> 
> thanks. it worked

Thanks it worked for M3

**Comment by fukyor** [comment]
> Try
> 
> pip3 install --upgrade --force-reinstall exrex
> 
> {OR }
> 
> Simply
> 
> pip3 uninstall exrex pip3 install exrex

yes,thanks it works

**Comment by Lambois** [comment]
thanks

**Comment by trumpsandhu1-blip** [comment]
# python3 oneforall.py -h
Traceback (most recent call last):
  File "/root/OneForAll/oneforall.py", line 11, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
                                             please friends help me
