### ISSUE TITLE
Traceback (most recent call last):   File "/home/kali/OneForAll/oneforall.py", line 16, in <module>     from brute import Brute   File "/home/kali/OneForAll/brute.py", line 14, in <module>     import exrex   File "/home/kali/.local/lib/python3.11/site-packages/exrex.py", line 25, in <module>     from re import sre_parse, U ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

### ISSUE THREAD

**Issue by MkashifShahid** [shmilylty/OneForAll#395]
**when Running this tools i got all time i have installed new machine but same issue** 
Traceback (most recent call last):
  File "/home/kali/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/home/kali/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/home/kali/.local/lib/python3.11/site-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)

**Comment by Lubberly** [comment]
same issue
