### ISSUE TITLE
Python 3.13.0用不了

### ISSUE THREAD

**Issue by danran12** [shmilylty/OneForAll#400]
![image](https://github.com/user-attachments/assets/85c11ed8-a9ee-41c3-a200-8935f3514aae)

**Comment by 3162164270** [comment]
我也是这个情况，请问解决了吗

**Comment by Morgan-earl** [comment]
在fire库里面找到个[Python 3.13 experimental support?](https://github.com/google/python-fire/issues/570) ，但视乎并没有看到有相关的PR。

**Comment by Morgan-earl** [comment]
> 在fire库里面找到个[Python 3.13 experimental support?](https://github.com/google/python-fire/issues/570) ，但视乎并没有看到有相关的PR。

找到了PR了，需要将Fire更新到0.7.0
[#444: Removed pipes dependency](https://github.com/google/python-fire/pull/447#issuecomment-2386138560)

**Comment by Misakait** [comment]
![PixPin_2025-01-08_16-48-46](https://github.com/user-attachments/assets/ce5df1f0-424d-4ee2-b305-fbf4f9ca9ef9)

**Comment by Xia0-0** [comment]
python3.13，不支持pipes了，无法下载依赖，我一开始用kali,被那个虚拟环境及依赖关系弄烦了，没做成，然后跑到主机windows11上来弄，通过 Chocolatey（一个 Windows 包管理器），安装 Python 3.7：

choco install python --version=3.7.9

再将命令更改下为，（管理员模式）
cd OneForAll/
py -3.7 -m pip install -U pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/
pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
py -3.7 oneforall.py --help

**Comment by Xia0-0** [comment]
不过之后运行都得用 pv -3.7 ...............

**Comment by Damashu** [comment]
怎么解决E:\shengtou_tool\oneforall\OneForAll-master>python oneforall.py --help
Traceback (most recent call last):
  File "E:\shengtou_tool\oneforall\OneForAll-master\oneforall.py", line 11, in <module>
    import fire
  File "E:\python\Lib\site-packages\fire\__init__.py", line 21, in <module>
    from fire.core import Fire
  File "E:\python\Lib\site-packages\fire\core.py", line 59, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'只能换旧的python版本了吗

**Comment by Xia0-0** [comment]
> 怎么解决E:\shengtou_tool\oneforall\OneForAll-master>python oneforall.py --help Traceback (most recent call last): File "E:\shengtou_tool\oneforall\OneForAll-master\oneforall.py", line 11, in import fire File "E:\python\Lib\site-packages\fire__init__.py", line 21, in from fire.core import Fire File "E:\python\Lib\site-packages\fire\core.py", line 59, in import pipes ModuleNotFoundError: No module named 'pipes'只能换旧的python版本了吗

暂时好像只能用旧版本的python环境了，高版本的得等项目方修正相关代码了😶‍🌫️😶‍🌫️

**Comment by blackcodersec** [comment]
Recently, I faced the same issue.

**Comment by Xia0-0** [comment]
> Recently, I faced the same issue.最近，我遇到了同样的问题。

3.13 以下版本的环境，我用的3.11的

**Comment by blackcodersec** [comment]
I am using `Python 3.13.2`

**Comment by Xia0-0** [comment]
> I am using `Python 3.13.2`我正在使用`Python 3.13.2`
降级吧亦或者再安装个低版本的环境

**Comment by blackcodersec** [comment]
Please fix this issue

**Comment by hifooyun** [comment]
Need change requirements.txt fire version 0.5.0 to 0.7.0 and exrex versioin0.10.5  to 0.12.0

**Comment by hifooyun** [comment]
需要把requirements.txt 的 fire版本改成0.7.0 、exrex版本改成0.12.0

**Comment by blackcodersec** [comment]
Could you update requirements.txt file?

**Comment by is-liuxi** [comment]
手动降级吧
https://www.cnblogs.com/LilRind/p/13505477.html

**Comment by DL668** [comment]
我直接一步到位搞到了3.7，就没啥问题了

**Comment by DOSTGHOST** [comment]
> 需要把requirements.txt 的 fire版本改成0.7.0 、exrex版本改成0.12.0
well done;thank you bro!

**Comment by Archerkong** [comment]
> 需要把requirements.txt 的 fire版本改成0.7.0 、exrex版本改成0.12.0

old bro 666

**Comment by FX42S** [comment]
u can uninstall old fire 0.4.0,and install new like:

root@locahost# pip uninstall fire
Found existing installation: fire 0.4.0
Uninstalling fire-0.4.0:
Would remove:
/home/fhoenix/.local/lib/python3.14/site-packages/fire-0.4.0.dist-info/*
/home/fhoenix/.local/lib/python3.14/site-packages/fire/*
Proceed (Y/n)? Y
Successfully uninstalled fire-0.4.0
root@locahost#
pip install fire
Defaulting to user installation because normal site-packages is not writeable
Collecting fire
Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: termcolor in /home/fhoenix/.local/lib/python3.14/site-packages (from fire) (1.1.0)
Downloading fire-0.7.1-py3-none-any.whl (115 kB)
Installing collected packages: fire
Successfully installed fire-0.7.1
