### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'

### ISSUE THREAD

**Issue by handbye** [shmilylty/OneForAll#5]
```
(hack) D:\haker\1-脚本\OneForAll\oneforall>python oneforall.py -target xj-tianye.com run
Traceback (most recent call last):
  File "oneforall.py", line 13, in <module>
    import config
  File "D:\haker\1-脚本\OneForAll\oneforall\config.py", line 195, in <module>
    sys.stderr.reconfigure(encoding='utf-8')
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'
```

**Comment by shmilylty** [comment]
提供一下系统版本，Python版本。

**Comment by shmilylty** [comment]
已解决
