### ISSUE TITLE
oneforall使用big_subnames.txt字典报错

### ISSUE THREAD

**Issue by ody5sey** [shmilylty/OneForAll#50]
**是否使用了最新代码**
是

**Bug描述**
把config第51行的subnames.txt改成big_subnames.txt会报错

**运行环境**
 - 系统：[macOS]（必写）
 - Python版本：[例如3.8.1]（必写）
 - OneForAll版本：[例如0.0.9]（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python oneforall.py example.com

**报错文本**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oneforall.py", line 251, in run
    self.main()
  File "oneforall.py", line 176, in main
    brute.run()
  File "/Users//PycharmProjects/oneforall/aiobrute.py", line 283, in run
    loop.run_until_complete(self.main(self.domain, rx_queue))
  File "/Users//.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users//PycharmProjects/oneforall/aiobrute.py", line 261, in main
    results = await resolve.aio_resolve(tasks, self.process, self.coroutine)
  File "/Users/PycharmProjects/oneforall/common/resolve.py", line 168, in aio_resolve
    return results
  File "/Users//.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 130, in __aexit__
    self.terminate()
  File "/Users//.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 277, in terminate
    self.close()
  File "/Users/.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 272, in close
    tx.put_nowait(None)
  File "/Users//.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/queues.py", line 132, in put_nowait
    return self.put(obj, False)
  File "/Users/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/queues.py", line 84, in put
    raise Full
queue.Full

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
使用命令有误，正确使用方式是：
```shell
python oneforall.py --target example.com run
```

**Comment by ody5sey** [comment]
我用了这个命令还是爆粗，这个错误看来是queue队列的有关，multiprocessing的queue队列无法负载这么庞大的数据

`  File "/Users/s1riu5/PycharmProjects/oneforall/common/resolve.py", line 167, in aio_resolve
    results = await pool.map(wrapped_query, subdomain_list)
  File "/Users/s1riu5/.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 251, in map
    tids = [self.queue_work(func, (item,), {}) for item in iterable]
  File "/Users/s1riu5/.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 251, in <listcomp>
    tids = [self.queue_work(func, (item,), {}) for item in iterable]
  File "/Users/s1riu5/.local/share/virtualenvs/oneforall-EpEYzA6i/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 197, in queue_work
    tx.put_nowait((task_id, func, args, kwargs))
  File "/Users/s1riu5/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/queues.py", line 132, in put_nowait
    return self.put(obj, False)
  File "/Users/s1riu5/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/queues.py", line 84, in put
    raise Full
queue.Full`

**Comment by shmilylty** [comment]
这个问题好像只会在macos上出现

**Comment by ody5sey** [comment]
嗯 测试的确是，可能macOS的系统存在限制
