### ISSUE TITLE
使用报lxml错误

### ISSUE THREAD

**Issue by 98Kstar** [shmilylty/OneForAll#51]
用了最新代码

全部更新代码，并安装了re文件内的依赖包，报错：
Exception in thread gitee:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/tools/OneForAll/oneforall/modules/search/gitee.py", line 70, in do
    query.run()
  File "/root/tools/OneForAll/oneforall/modules/search/gitee.py", line 56, in run
    self.search()
  File "/root/tools/OneForAll/oneforall/modules/search/gitee.py", line 36, in search
    soup = BeautifulSoup(resp.text, 'lxml')
  File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**运行环境**
 - 系统：centos
 - Python版本：python3.8.0a1
 - OneForAll版本：最新版
 
**如何复现**
python3 oneforall --target xxx.com run 
中间有两段会报错
**报错文本**
复制完整的报错文本（必写）
Exception in thread baidu:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/tools/OneForAll/oneforall/modules/search/baidu.py", line 105, in do
    search.run()
  File "/root/tools/OneForAll/oneforall/modules/search/baidu.py", line 78, in run
    self.search(self.domain, full_search=True)
  File "/root/tools/OneForAll/oneforall/modules/search/baidu.py", line 55, in search
    subdomains = self.redirect_match(domain, resp.text)
  File "/root/tools/OneForAll/oneforall/modules/search/baidu.py", line 24, in redirect_match
    bs = BeautifulSoup(html, features='lxml')
  File "/usr/local/lib/python3.8/site-packages/bs4/__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

![image](https://user-images.githubusercontent.com/41816999/75273364-b1f29000-583b-11ea-8c84-4c18fdd51d1f.png)
![image](https://user-images.githubusercontent.com/41816999/75273391-bcad2500-583b-11ea-9610-1546c5d93a8d.png)
![image](https://user-images.githubusercontent.com/41816999/75273413-c767ba00-583b-11ea-935e-12925aa11a31.png)

*预期结果**
别报错就行，如何解决）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
应该是你安装的lxml依赖的命令有问题，没有安装到python3.8的有关路径。
如果你的系统有多个python版本，你要注意检查一下。
