### ISSUE TITLE
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol 

### ISSUE THREAD

**Issue by aaeolus** [shmilylty/OneForAll#6]
在运行的时候总是爆如下错误，看样子是异步模块里的SSL问题，不知道如何解决

14:46:11,060 [INFOR] request:24 - 使用medium等端口范围
14:46:11,060 [INFOR] request:32 - 正在生成请求地址
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x10c6288d0>
transport: <_SelectorSocketTransport fd=32 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x10c6288d0>
-------------------
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x10c6d97b8>
transport: <_SelectorSocketTransport closing fd=53 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1056)

**Comment by shmilylty** [comment]
提供一下运行环境信息

**Comment by aaeolus** [comment]
macos

**Comment by shmilylty** [comment]
现在已经改为[暂时不探测https](https://github.com/shmilylty/OneForAll/commit/c2679a6ceb3e3b2f6bce82a29303f4a75e23dad2)，你可以更新一下项目试一下，欢迎加群交流。

**Comment by aaeolus** [comment]
现在可以了
