### ISSUE TITLE
运行报错row.pop('header')  KeyError: 'header'

### ISSUE THREAD

**Issue by shadow1ng** [shmilylty/OneForAll#69]
**是否使用了最新代码**
是

**Bug描述**
运行python3 oneforall.py --target sxzq.com run后
报错提示
  File "D:\tools\oneforall\common\utils.py", line 325, in export_all
    row.pop('header')
KeyError: 'header'

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.8.1
 - OneForAll版本：v0.1.0#dev    2020.4.21下载
 
**如何复现**
复现命令
python3 oneforall.py --target sxzq.com run
**报错文本**
Traceback (most recent call last):
  File "oneforall.py", line 249, in <module>
    fire.Fire(OneForAll)
  File "C:\Program Files\Python38\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Program Files\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Program Files\Python38\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 237, in run
    utils.export_all(self.format, self.path, self.datas)
  File "D:\tools\oneforall\common\utils.py", line 325, in export_all
    row.pop('header')
KeyError: 'header'

**屏幕截图**
完整OneForAll执行流程截图
![image](https://user-images.githubusercontent.com/39651966/79868594-b3db6880-8412-11ea-947f-e97b14c742b6.png)

![image](https://user-images.githubusercontent.com/39651966/79868205-29930480-8412-11ea-8799-c9d026ca73b3.png)

**Comment by shmilylty** [comment]
@shadow1ng 你重新测试一下呢

**Comment by shmilylty** [comment]
已修复
