### ISSUE TITLE
Parent module 'modules.certificates' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by l3m0n** [shmilylty/OneForAll#8]
**是否使用了最新代码**
是

**Bug描述**
包导入路径不对

**如何复现**
复现步骤（可不写）
复现命令
python3 oneforall.py --target xx.com

**预期结果**
清晰而简洁的预期结果描述（可不写）

**实际结果**
importlib.import_module('.'+name, package)
包的导入路径问题

**屏幕截图**

**运行环境**
 - 系统：mac
 - Python版本：3.6.1

**报错文本**
```
Traceback (most recent call last):
  File "oneforall.py", line 161, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 154, in run
    self.main()
  File "oneforall.py", line 96, in main
    collect.run()
  File "/Users/xx/study/github/OneForAll/oneforall/collect.py", line 58, in run
    self.import_func()
  File "/Users/xx/study/github/OneForAll/oneforall/collect.py", line 48, in import_func
    import_object = importlib.import_module('.'+name, package)
  File "/usr/local/Cellar/python/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 973, in _gcd_import
  File "<frozen importlib._bootstrap>", line 923, in _sanity_check
SystemError: Parent module 'modules.certificates' not loaded, cannot perform relative import
```

**Comment by shmilylty** [comment]
柠檬师傅先暂时升级Python版本到3.7试试呢，我之后解决这个bug。
