### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by z3dc0ps** [shmilylty/OneForAll#80]
Traceback (most recent call last):
  File "oneforall.py", line 250, in <module>
    fire.Fire(OneForAll)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 237, in run
    self.main()
  File "oneforall.py", line 193, in main
    self.data = resolve.run_resolve(self.domain, self.data)
  File "/root/Desktop/bug/subdomain/scan/OneForAll/oneforall/common/resolve.py", line 167, in run_resolve
    data = update_data(data, records)
  File "/root/Desktop/bug/subdomain/scan/OneForAll/oneforall/common/resolve.py", line 42, in update_data
    items.update(record)
TypeError: 'NoneType' object is not iterable

**Comment by satishkmr834** [comment]
yes getting this same error from last 2 days please solve this problem quickly 
your tool is amazing by the way, its super fast and it gives 100% correct result.
please solve the error as soon as possible.
thank you

**Comment by K0Z3R0** [comment]
I'm also having this issue. Love the tool, keep up the good work. If you want a quick fix you could try one of the solutions here https://stackoverflow.com/questions/3887381/typeerror-nonetype-object-is-not-iterable-in-python

**Comment by shmilylty** [comment]
@K0Z3R0 @satishkmr834 @z3dc0ps Hi, I have fix this bug.

**Comment by satishkmr834** [comment]
Yeah, its working fine now

thankyou very much
