### ISSUE TITLE
获取子域名结果为空时异常退出

### ISSUE THREAD

**Issue by sureiam** [shmilylty/OneForAll#90]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）

**Bug描述**
批量从txt读入域名跑的时候，似乎如果中间某个域名查询结果为空时，程序会直接报错退出。这个是不应该提示没有获取到结果然后跳过这个域名。以下为报错信息。

Traceback (most recent call last):
  File "oneforall.py", line 250, in <module>
    fire.Fire(OneForAll)
  File "/Users/heiheihei/Library/Python/3.7/lib/python/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/heiheihei/Library/Python/3.7/lib/python/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/Users/heiheihei/Library/Python/3.7/lib/python/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 237, in run
    self.main()
  File "oneforall.py", line 193, in main
    self.data = resolve.run_resolve(self.domain, self.data)
  File "/Users/heiheihei/tools/1.信息收集/OneForAll/oneforall/common/resolve.py", line 167, in run_resolve
    data = update_data(data, records)
  File "/Users/heiheihei/tools/1.信息收集/OneForAll/oneforall/common/resolve.py", line 42, in update_data
    items.update(record)
TypeError: 'NoneType' object is not iterable

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.0.6]（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
最新版本OneForAll已经解决了这个问题，请更新后再次试试。

**Comment by sureiam** [comment]
哇，这个更新真的快哦，实在不好意思。
