### ISSUE TITLE
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] 

### ISSUE THREAD

**Issue by si9int** [shmilylty/OneForAll#93]
On a certain step the `asyncio/sslproto` library drops errors regarding thee handshake. I recommend catching these or trying to find a solution for this issue (didn't look into the code).

```
Request Progress:   6%|█▌                       | 8/130 [00:00<00:12,  9.47it/s]SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1990403da0>
transport: <_SelectorSocketTransport fd=40 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1990403da0>
transport: <_SelectorSocketTransport closing fd=40 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1056)
Request Progress:  15%|███▋                    | 20/130 [00:00<00:06, 16.24it/s]SSL handshake failed
```

**Comment by shmilylty** [comment]
Please use Python 3.8 or above
